// SPDX-License-Identifier: MIT
// Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.

/**
 * Example: Complete integration of tile_engine kernels with dispatcher via codegen
 * 
 * This example shows the full workflow:
 * 1. tile_engine generates GEMM kernels
 * 2. Codegen creates dispatcher wrappers
 * 3. Application registers and uses kernels via dispatcher
 */

#include "ck_tile/dispatcher.hpp"

// Include the auto-generated registration header
// This is created by generate_dispatcher_wrappers.py
#include "generated/register_all_kernels.hpp"

#include <iostream>
#include <vector>

using namespace ck_tile::dispatcher;

void example_automatic_registration()
{
    std::cout << "=== Automatic Registration Example ===\n";
    
    // One-line registration of all tile_engine GEMM kernels
    register_all_tile_gemm_kernels(942);  // gfx942
    
    auto& registry = Registry::instance();
    std::cout << "Registered " << registry.size() << " kernels\n";
    std::cout << "Expected: " << get_tile_gemm_kernel_count() << " kernels\n";
}

void example_query_registered_kernels()
{
    std::cout << "\n=== Query Registered Kernels ===\n";
    
    auto& registry = Registry::instance();
    auto all_kernels = registry.get_all();
    
    std::cout << "Available kernels:\n";
    for (size_t i = 0; i < std::min(all_kernels.size(), size_t(5)); ++i) {
        auto& kernel = all_kernels[i];
        const auto& key = kernel->get_key();
        
        std::cout << "  [" << i << "] " << kernel->get_name() << "\n";
        std::cout << "      Tile: " << key.algorithm.tile_shape.m << "x"
                  << key.algorithm.tile_shape.n << "x"
                  << key.algorithm.tile_shape.k << "\n";
        std::cout << "      Pipeline: " << static_cast<int>(key.algorithm.pipeline) << "\n";
        std::cout << "      Persistent: " << (key.algorithm.persistent ? "yes" : "no") << "\n";
    }
    
    if (all_kernels.size() > 5) {
        std::cout << "  ... and " << (all_kernels.size() - 5) << " more\n";
    }
}

void example_filter_by_criteria()
{
    std::cout << "\n=== Filter Kernels by Criteria ===\n";
    
    auto& registry = Registry::instance();
    
    // Find all persistent kernels
    auto persistent = registry.filter([](const KernelInstance& k) {
        return k.get_key().algorithm.persistent;
    });
    std::cout << "Persistent kernels: " << persistent.size() << "\n";
    
    // Find all large tile kernels (>= 256x256)
    auto large_tiles = registry.filter([](const KernelInstance& k) {
        const auto& tile = k.get_key().algorithm.tile_shape;
        return tile.m >= 256 && tile.n >= 256;
    });
    std::cout << "Large tile (>=256x256) kernels: " << large_tiles.size() << "\n";
    
    // Find all CompV4 pipeline kernels
    auto compv4 = registry.filter([](const KernelInstance& k) {
        return k.get_key().algorithm.pipeline == Pipeline::CompV4;
    });
    std::cout << "CompV4 pipeline kernels: " << compv4.size() << "\n";
}

void example_dispatcher_selection()
{
    std::cout << "\n=== Dispatcher Selection Example ===\n";
    
    Dispatcher dispatcher;
    
    // Test different problem sizes
    std::vector<std::tuple<int, int, int>> problems = {
        {1024, 1024, 1024},
        {2048, 2048, 1024},
        {4096, 4096, 2048},
        {512, 512, 512}
    };
    
    for (const auto& [M, N, K] : problems) {
        Problem problem(M, N, K);
        auto kernel = dispatcher.select_kernel(problem);
        
        if (kernel) {
            std::cout << "Problem " << M << "x" << N << "x" << K 
                      << " -> " << kernel->get_name() << "\n";
        } else {
            std::cout << "Problem " << M << "x" << N << "x" << K 
                      << " -> No suitable kernel\n";
        }
    }
}

void example_explicit_selection()
{
    std::cout << "\n=== Explicit Kernel Selection ===\n";
    
    auto& registry = Registry::instance();
    
    // Get a specific kernel by identifier
    // (This would be generated by the kernel's encode_identifier())
    auto all_kernels = registry.get_all();
    if (!all_kernels.empty()) {
        const auto& first_kernel = all_kernels[0];
        std::string identifier = first_kernel->get_key().encode_identifier();
        
        std::cout << "Looking up kernel by identifier: " << identifier << "\n";
        
        auto found = registry.lookup(identifier);
        if (found) {
            std::cout << "  Found: " << found->get_name() << "\n";
            
            // Check if it supports a problem
            Problem problem(1024, 1024, 1024);
            if (found->supports(problem)) {
                std::cout << "  Supports 1024x1024x1024: yes\n";
            } else {
                std::cout << "  Supports 1024x1024x1024: no\n";
            }
        }
    }
}

void example_statistics()
{
    std::cout << "\n=== Kernel Statistics ===\n";
    
    auto& registry = Registry::instance();
    auto all_kernels = registry.get_all();
    
    // Count by pipeline
    int mem = 0, compv3 = 0, compv4 = 0;
    for (const auto& k : all_kernels) {
        switch (k->get_key().algorithm.pipeline) {
            case Pipeline::Mem: mem++; break;
            case Pipeline::CompV3: compv3++; break;
            case Pipeline::CompV4: compv4++; break;
            default: break;
        }
    }
    
    std::cout << "Pipeline distribution:\n";
    std::cout << "  Mem: " << mem << "\n";
    std::cout << "  CompV3: " << compv3 << "\n";
    std::cout << "  CompV4: " << compv4 << "\n";
    
    // Count by scheduler
    int intrawave = 0, interwave = 0;
    for (const auto& k : all_kernels) {
        switch (k->get_key().algorithm.scheduler) {
            case Scheduler::Intrawave: intrawave++; break;
            case Scheduler::Interwave: interwave++; break;
            default: break;
        }
    }
    
    std::cout << "Scheduler distribution:\n";
    std::cout << "  Intrawave: " << intrawave << "\n";
    std::cout << "  Interwave: " << interwave << "\n";
}

int main()
{
    std::cout << "=== Dispatcher Codegen Integration Example ===\n\n";
    
    // Step 1: Register all tile_engine kernels
    example_automatic_registration();
    
    // Step 2: Query what's available
    example_query_registered_kernels();
    
    // Step 3: Filter by criteria
    example_filter_by_criteria();
    
    // Step 4: Use dispatcher for selection
    example_dispatcher_selection();
    
    // Step 5: Explicit kernel lookup
    example_explicit_selection();
    
    // Step 6: Statistics
    example_statistics();
    
    std::cout << "\n=== Example Complete ===\n";
    
    return 0;
}

