#!/usr/bin/env python3
# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT


# This script generate list of files that are not referenced from any test (list in JSON format)
# Script only looks at not referenced files from three directories: include, library and profiler
# CK needs to be built with ability to use dependency parser and generate dependencies

# Usage: python3 generate_list_of_files_not_referenced_in_tests -f /path/to/enhanced_dependency_mapping/json/file

import argparse
import os
import subprocess
import json


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-f",
        required=True,
        help="Path to enhanced_dependency_mapping.json file generated by dependency parser",
    )
    args = parser.parse_args()
    return args


def main():
    args = parse_args()

    with open(args.f, "r") as file:
        ref_files = json.load(file)
    file_to_executables = ref_files["file_to_executables"]

    # Determine the CK project root: go up two levels from this script's location
    # (script/dependency-parser/ -> script/ -> CK root)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    ck_root = os.path.normpath(os.path.join(script_dir, "..", ".."))

    search_dirs = ["include", "library", "profiler"]
    all_files = []
    for d in search_dirs:
        search_path = os.path.join(ck_root, d)
        if not os.path.isdir(search_path):
            print(f"Warning: directory not found: {search_path}")
            continue
        result = subprocess.check_output(
            f'find "{search_path}" -type f -iname "*.cpp" -o -iname "*.hpp"',
            shell=True,
        ).decode("utf-8").split("\n")
        # Convert absolute paths to relative paths from CK root
        ck_root_prefix = ck_root.rstrip("/") + "/"
        for f in result:
            f = f.strip()
            if f:
                if f.startswith(ck_root_prefix):
                    f = f[len(ck_root_prefix):]
                all_files.append(f)

    all_referenced_files = []
    for v in file_to_executables:
        # Match both standalone paths (include/, library/, profiler/) and
        # monorepo paths (projects/composablekernel/include/, etc.)
        if any(
            d in v
            for d in ["include/", "library/", "profiler/"]
        ):
            exe_list = file_to_executables[v]
        else:
            continue

        found = any("bin/test_" in el for el in exe_list)
        if found:
            all_referenced_files.append(v)

    not_referenced_files = {"include": [], "library": [], "profiler": []}
    for f in all_files:
        # Check if this file appears in any referenced file path
        # (handles both relative and monorepo-prefixed paths)
        found = any(f in el or el.endswith(f) for el in all_referenced_files)
        if not found:
            pos = f.find("/")
            if pos > 0 and f[:pos] in not_referenced_files:
                not_referenced_files[f[:pos]].append(f)

    print(json.dumps(not_referenced_files, indent="\t"))


if __name__ == "__main__":
    main()
