# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-22.04"

sphinx:
   configuration: docs/conf.py

formats: [htmlzip]

python:
   version: "3.10"
   install:
   - requirements: docs/.sphinx/requirements.txt
