ARG BASE_DOCKER="rocm/pytorch:latest"
FROM $BASE_DOCKER
RUN pip install pandas zmq einops && \
    pip install numpy==1.26.2 && \
    cd /var/lib/jenkins && \
    rm -rf aiter && \
    git clone --recursive https://github.com/ROCm/aiter.git && \
    cd aiter && \
    rm -rf 3rdparty/composable_kernel/ && \
    git clone https://github.com/ROCm/composable_kernel.git 3rdparty/composable_kernel/ && \
    python3 setup.py develop && \
    chown -R jenkins:jenkins /var/lib/jenkins && \
    sudo usermod -aG irc jenkins
