[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "rocm-composable-kernel"
dynamic = ["version"]
description = "Composable Kernel, performance-critical kernels for machine learning workloads"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []

[project.urls]
"Homepage" = "https://github.com/rocm/composable_kernel"
"Bug Tracker" = "https://github.com/rocm/composable_kernel/issues"

[tool.setuptools]

packages = [
    "genck", 
    "genck.ops",
    "genck.ops.ck_tile",
    "genck.ops.ck_tile.gemm",
    "genck.emitters",
    "ck4inductor", 
    "ck4inductor.include", 
    "ck4inductor.library", 
    "ck4inductor.universal_gemm", 
    "ck4inductor.batched_universal_gemm", 
    "ck4inductor.grouped_conv_fwd"
]

[tool.setuptools.package-dir]

genck = "python/codegen"
"genck.ops" = "python/codegen/ops"
"genck.ops.ck_tile" = "python/codegen/ops/ck_tile"
"genck.ops.ck_tile.gemm" = "python/codegen/ops/ck_tile/gemm"
"genck.emitters" = "python/codegen/emitters"
ck4inductor = "python/ck4inductor"
"ck4inductor.universal_gemm" = "python/ck4inductor/universal_gemm"
"ck4inductor.batched_universal_gemm" = "python/ck4inductor/batched_universal_gemm"
"ck4inductor.grouped_conv_fwd" = "python/ck4inductor/grouped_conv_fwd"
"ck4inductor.include" = "include"
"ck4inductor.library" = "library"

[tool.setuptools.package-data]
"ck4inductor.include" = ["ck/**/*.hpp"]
"ck4inductor.library" = [
    "src/tensor_operation_instance/gpu/gemm_universal/device_gemm_xdl_universal_*/*.hpp", 
    "src/tensor_operation_instance/gpu/gemm_universal_batched/**/*.hpp", 
    "include/ck/library/tensor_operation_instance/gpu/grouped_conv_fwd/**/*.hpp"
]

[tool.setuptools.dynamic]
version = { attr = "setuptools_scm.get_version" }
