// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2025, Advanced Micro Devices, Inc. All rights reserved.

#include "unified_attention.hpp"
#include "unified_attention_impl.hpp"
#include "mask.hpp"

namespace ck_tile {

std::ostream& operator<<(std::ostream& stream,
                         const unified_attention_args::data_type_enum& data_type)
{
    switch(data_type)
    {
    case unified_attention_args::data_type_enum::fp16: return stream << "fp16";
    case unified_attention_args::data_type_enum::bf16: return stream << "bf16";
    case unified_attention_args::data_type_enum::fp8: return stream << "fp8";
    default: return stream << "unknown";
    }
}

// =============================================================================
// Config selection
//
// The job is split in two halves so each is small enough to read in one sitting:
//
//   1. select_config(args)
//        - Reads shape (hdim, num_queries_per_kv, avg_q, max_seqlen_q) and
//          picks one of the KernelVariants defined in unified_attention_impl.hpp.
//          KernelVariant is the only place where compile-time knobs live —
//          changing a knob means adding/editing a variant_config<V>.
//
//   2. dispatch_variant<V>() + the final switch
//        - dispatch_variant<V>() is a single function template that fans out
//          over (dtype, mask) and forwards into the per-instance dispatch
//          function generated by INST_UNIFIED_ATTENTION_DISPATCH.
//        - The final switch maps KernelVariant -> dispatch_variant<V>.
//
// page_size is intentionally NOT part of the config — the multi-page-tile
// pipeline fix made kBlockN independent of runtime page_blk_size, so every
// variant is correct for any page size.
// =============================================================================

struct KernelConfig
{
    KernelVariant variant;
    bool          unsupported = false;
};

KernelConfig select_config(const unified_attention_args& args)
{
    KernelConfig cfg;

    // The variants are now num_queries_per_kv-agnostic (kBlockQ is runtime
    // inside the kernel) -- we just have to pick a kBlockM that holds enough
    // rows for `num_qpkv * max_q` and that num_qpkv divides cleanly.
    //
    // `avg_q * num_qpkv` is the *effective* per-CTA tile occupancy; e.g.
    // GQA-8 with sq=1 produces 8 rows per Q tile, the same as MHA with sq=8.
    // Tiering on that quantity lets one variant ladder serve both regimes.
    const index_t num_qpkv  = args.num_queries_per_kv;
    const index_t avg_q     = args.num_seqs > 0 ? args.num_tokens / args.num_seqs
                                                : args.num_tokens;
    const index_t max_q     = args.max_seqlen_q > 0 ? args.max_seqlen_q : avg_q;
    const index_t avg_rows  = avg_q * num_qpkv; // effective rows per Q tile
    const index_t max_rows  = max_q * num_qpkv;

    if(args.hdim == 128)
    {
        // d=128 ladder: m16 / m32 / m128 / prefill (m256). Requires
        // num_qpkv to divide the chosen kBlockM, which is automatic for
        // num_qpkv in {1, 2, 4, 8, 16} and any of the kBlockM's below.
        if(avg_rows <= 16 && max_rows <= 16)
            cfg.variant = KernelVariant::decode_d128_m16;
        else if(avg_rows <= 32 && max_rows <= 32)
            cfg.variant = KernelVariant::decode_d128_m32;
        else if(avg_rows <= 128 && max_rows <= 128)
            cfg.variant = KernelVariant::decode_d128_m128;
        else
            cfg.variant = KernelVariant::prefill_d128;
        return cfg;
    }

    if(args.hdim == 64)
    {
        // d=64 ladder: m16 / m64 / m128 / prefill (m256). Same shape
        // selection logic as d=128; the variant's kBlockN is just bigger.
        if(avg_rows <= 16 && max_rows <= 16)
            cfg.variant = KernelVariant::decode_d64_m16;
        else if(avg_rows <= 64 && max_rows <= 64)
            cfg.variant = KernelVariant::decode_d64_m64;
        else if(avg_rows <= 128 && max_rows <= 128)
            cfg.variant = KernelVariant::decode_d64_m128;
        else
            cfg.variant = KernelVariant::prefill_d64;
        return cfg;
    }

    cfg.unsupported = true;
    return cfg;
}

// -----------------------------------------------------------------------------
// dispatch_variant<V>
//
// One function template. Fans out over (dtype, mask) and forwards into the
// per-instance dispatch generated by INST_UNIFIED_ATTENTION_DISPATCH. No
// per-variant boilerplate.
// -----------------------------------------------------------------------------
namespace {

// ---------------------------------------------------------------------------
// dispatch_one — call into a single compiled instance.
// ---------------------------------------------------------------------------
template <KernelVariant V,
          unified_attention_args::data_type_enum DType,
          bool IsMask,
          index_t PageSize>
std::pair<bool, float> dispatch_one(const unified_attention_args& args,
                                    const stream_config& config)
{
    return unified_attention_kernel_dispatch<
        unified_attention_kernel_traits<V, DType, IsMask, PageSize>>(args, config);
}

// Per-(V, DType) availability of IsLocal=true (Sliding-Window-Attention)
// instances. Phase 3 ships the four large-tier prefill instances; everything
// else returns {false, 0.f} so the host falls back to Triton (or whatever
// downstream caller handles the negative dispatch result).
//
// The Phase 3 SWA instances are all compiled at PageSize=0 (runtime page
// size) — the page-pinned ps16/ps32/ps64 menu only exists for the IsLocal=
// false fast path. SWA on Phase-5 (decode tiers) will follow the same rule
// unless the perf gate proves otherwise.
template <KernelVariant V, unified_attention_args::data_type_enum DType>
std::pair<bool, float> dispatch_local(const unified_attention_args& args,
                                      const stream_config& config)
{
    using DT = unified_attention_args::data_type_enum;
    // SWA availability matrix as of Phase 5:
    //   prefill_d128 / prefill_d64                — large-tier prefill (Phase 3)
    //   decode_d64_m128 / decode_d64_m16          — GPT-OSS shapes  (Phase 5)
    // For all of them we only compile {bf16, fp16}; fp8 SWA is a future
    // phase. Anything else (decode_d128_*, decode_d64_m64, …) still falls
    // back to {false, 0.f} so the aiter wrapper picks Triton.
    constexpr bool is_supported_variant =
        (V == KernelVariant::prefill_d128 ||
         V == KernelVariant::prefill_d64 ||
         V == KernelVariant::decode_d64_m128 ||
         V == KernelVariant::decode_d64_m16);
    if constexpr(is_supported_variant && (DType == DT::bf16 || DType == DT::fp16))
    {
        return unified_attention_kernel_dispatch<
            unified_attention_kernel_traits<V, DType, /*IsMasking=*/true,
                                            /*kPageSize=*/0,
                                            /*IsLocal=*/true>>(args, config);
    }
    else
    {
        return {false, 0.f};
    }
}

// ---------------------------------------------------------------------------
// dispatch_page_size — pick the constexpr `kPageSize` instance.
//
// For prefill variants (prefill_d128 / prefill_d64) we compile a small
// menu of constexpr-page-size instances for the values vLLM/SGLang actually
// configure ({16, 32, 64}). The runtime switch on args.page_blk_size routes
// to the matching one; anything else (or any non-prefill variant) goes to
// the PageSize=0 catch-all that keeps the legacy runtime-page-size code.
//
// The fast-path payoff is two-fold:
//   1. Compile-time `page_size` lets the compiler strength-reduce every
//      `/ page_size`, `* page_size`, and `% page_size` inside the per-tile
//      address chain. div-by-32 collapses to `shr 5`, etc.
//   2. The Tier-0 / Tier-2 gate uses the *real* `KY0_step_N <= kPageSize`
//      precondition instead of the conservative `<= 16` hedge, so
//      prefill_d128 bf16/fp16, prefill_d64 bf16/fp16/fp8 also enter the
//      scalar-promote + LDS-cache fast path at their natural page sizes.
// ---------------------------------------------------------------------------
template <KernelVariant V,
          unified_attention_args::data_type_enum DType,
          bool IsMask>
std::pair<bool, float> dispatch_page_size(const unified_attention_args& args,
                                          const stream_config& config)
{
    if constexpr(V == KernelVariant::prefill_d128 ||
                 V == KernelVariant::prefill_d64)
    {
        switch(args.page_blk_size)
        {
            case 16: return dispatch_one<V, DType, IsMask, 16>(args, config);
            case 32: return dispatch_one<V, DType, IsMask, 32>(args, config);
            case 64: return dispatch_one<V, DType, IsMask, 64>(args, config);
            default: return dispatch_one<V, DType, IsMask, 0>(args, config);
        }
    }
    else
    {
        // Decode variants stay on the runtime-page-size path — they don't
        // benefit from the Tier-0/Tier-2 gate (too few warps for the scalar-
        // promote payoff) and the binary-size cost isn't justified.
        return dispatch_one<V, DType, IsMask, 0>(args, config);
    }
}

template <KernelVariant V>
std::pair<bool, float> dispatch_variant(const unified_attention_args& args,
                                        const stream_config& config)
{
    using DT           = unified_attention_args::data_type_enum;
    const bool is_mask = (args.mask_type != static_cast<int>(mask_enum::no_mask));
    // SWA criterion mirrors the FA-style left/right window semantics: the
    // mask is "local" iff at least one bound is finite. `window_size_left
    // = -1` means "no left bound" (i.e. full causal), and
    // `window_size_right = 0` is the default causal anchor. Any other
    // combination opts into IsLocal=true.
    const bool is_local =
        is_mask && (args.window_size_left >= 0 || args.window_size_right > 0);

    if(args.data_type == DT::fp16)
    {
        if(is_local) return dispatch_local<V, DT::fp16>(args, config);
        if(is_mask)  return dispatch_page_size<V, DT::fp16, true >(args, config);
        return            dispatch_page_size<V, DT::fp16, false>(args, config);
    }
    if(args.data_type == DT::bf16)
    {
        if(is_local) return dispatch_local<V, DT::bf16>(args, config);
        if(is_mask)  return dispatch_page_size<V, DT::bf16, true >(args, config);
        return            dispatch_page_size<V, DT::bf16, false>(args, config);
    }
    if(args.data_type == DT::fp8)
    {
        // FP8 is enabled on EVERY UA variant: prefill_d{64,128} and all
        // decode_d{64,128}_m{16,32,64,128} tiers. The `fmha_alu1`
        // P-tile re-layout in unified_attention_pipeline.hpp now goes
        // through LDS (store with QK-C distribution -> block sync ->
        // load with PV-A distribution) which is layout-agnostic and
        // covers both the 32x32x16 MFMA shapes (prefill +
        // decode_m{32,64,128}) and the 16x16x32 MFMA shape used by
        // the m16 tiny-decode tier — no per-shape per-thread
        // analysis required.
        if constexpr(V == KernelVariant::prefill_d128 ||
                     V == KernelVariant::decode_d128_m128 ||
                     V == KernelVariant::decode_d128_m32 ||
                     V == KernelVariant::decode_d128_m16 ||
                     V == KernelVariant::prefill_d64 ||
                     V == KernelVariant::decode_d64_m128 ||
                     V == KernelVariant::decode_d64_m64 ||
                     V == KernelVariant::decode_d64_m16)
        {
            if(is_mask)  return dispatch_page_size<V, DT::fp8, true >(args, config);
            return            dispatch_page_size<V, DT::fp8, false>(args, config);
        }
        return {false, -1.f};
    }
    return {false, -1.f};
}

} // anonymous namespace

std::pair<bool, float> unified_attention(const unified_attention_args& args,
                                         const stream_config& config)
{
    const auto cfg = select_config(args);

    if(cfg.unsupported)
    {
        std::cerr << "unified_attention: no matching kernel instance for hdim=" << args.hdim
                  << " num_queries_per_kv=" << args.num_queries_per_kv
                  << " data_type=" << args.data_type << " mask_type=" << args.mask_type
                  << std::endl;
        return std::make_pair(false, -1.f);
    }

    switch(cfg.variant)
    {
    case KernelVariant::prefill_d128:
        return dispatch_variant<KernelVariant::prefill_d128>(args, config);
    case KernelVariant::decode_d128_m128:
        return dispatch_variant<KernelVariant::decode_d128_m128>(args, config);
    case KernelVariant::decode_d128_m32:
        return dispatch_variant<KernelVariant::decode_d128_m32>(args, config);
    case KernelVariant::decode_d128_m16:
        return dispatch_variant<KernelVariant::decode_d128_m16>(args, config);
    case KernelVariant::prefill_d64:
        return dispatch_variant<KernelVariant::prefill_d64>(args, config);
    case KernelVariant::decode_d64_m128:
        return dispatch_variant<KernelVariant::decode_d64_m128>(args, config);
    case KernelVariant::decode_d64_m64:
        return dispatch_variant<KernelVariant::decode_d64_m64>(args, config);
    case KernelVariant::decode_d64_m16:
        return dispatch_variant<KernelVariant::decode_d64_m16>(args, config);
    }
    return std::make_pair(false, -1.f);
}

} // namespace ck_tile
