// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

/**
 * @file test_pooling_simple.cpp
 * @brief Unit tests for pooling kernels generated by pooling_instance_builder
 *
 * This test includes kernels generated during CMake configuration by
 * pooling_instance_builder.py and tests them with problem sizes extracted
 * from the corresponding JSON configuration files.
 */

#include <gtest/gtest.h>
#include <iostream>
#include <string>
#include <vector>

#include "ck_tile/core.hpp"
#include "ck_tile/host.hpp"
#include "ck_tile/ops/pooling.hpp"
#include "ck_tile/host/reference/reference_pool.hpp"
#include "tile_engine/ops/pooling/pooling_common.hpp"

// The kernel header is included via compile command line with -include flag
// It defines: SelectedKernel, KERNEL_NAME, InDataType, OutDataType,
//             ComputeDataType, IndexDataType, ReduceOpType,
//             TensorShape, WindowShape, POOLING_DIM

// ============================================================================
// Test parameter structures
// ============================================================================

/// @brief Test parameters for 2D pooling
struct PoolTestParams2D
{
    int N, H, W, C;              // Input dimensions (NHWC)
    int Y, X;                    // Window size
    int stride_h, stride_w;      // Strides
    int dilation_h, dilation_w;  // Dilations
    int pad_h_left, pad_h_right; // Height padding
    int pad_w_left, pad_w_right; // Width padding
};

/// @brief Test parameters for 3D pooling
struct PoolTestParams3D
{
    int N, D, H, W, C;                      // Input dimensions (NDHWC)
    int Z, Y, X;                            // Window size
    int stride_d, stride_h, stride_w;       // Strides
    int dilation_d, dilation_h, dilation_w; // Dilations
    int pad_d_left, pad_d_right;            // Depth padding
    int pad_h_left, pad_h_right;            // Height padding
    int pad_w_left, pad_w_right;            // Width padding
};

// Include config-specific test parameters (after parameter structs are defined)
#ifdef POOLING_TEST_PARAMS_HPP
#include POOLING_TEST_PARAMS_HPP
#endif

// ============================================================================
// 2D Pooling Tests
// ============================================================================

class PoolingTileEngineTest2D : public ::testing::TestWithParam<PoolTestParams2D>
{
    protected:
    void SetUp() override
    {
        auto params  = GetParam();
        N_           = params.N;
        H_           = params.H;
        W_           = params.W;
        C_           = params.C;
        Y_           = params.Y;
        X_           = params.X;
        stride_h_    = params.stride_h;
        stride_w_    = params.stride_w;
        dilation_h_  = params.dilation_h;
        dilation_w_  = params.dilation_w;
        pad_h_left_  = params.pad_h_left;
        pad_h_right_ = params.pad_h_right;
        pad_w_left_  = params.pad_w_left;
        pad_w_right_ = params.pad_w_right;

        // Calculate output dimensions
        ck_tile::index_t Ys = (Y_ - 1) * dilation_h_ + 1;
        ck_tile::index_t Xs = (X_ - 1) * dilation_w_ + 1;
        Ho_                 = (H_ + pad_h_left_ + pad_h_right_ - Ys) / stride_h_ + 1;
        Wo_                 = (W_ + pad_w_left_ + pad_w_right_ - Xs) / stride_w_ + 1;
    }

    int N_, H_, W_, C_;
    int Y_, X_;
    int stride_h_, stride_w_;
    int dilation_h_, dilation_w_;
    int pad_h_left_, pad_h_right_;
    int pad_w_left_, pad_w_right_;
    int Ho_, Wo_;
};

TEST_P(PoolingTileEngineTest2D, BasicFunctionality)
{
    // Create host tensors
    ck_tile::HostTensor<InDataType> h_in({N_, H_, W_, C_});
    ck_tile::HostTensor<OutDataType> h_out({N_, Ho_, Wo_, C_});
    ck_tile::HostTensor<OutDataType> h_out_ref({N_, Ho_, Wo_, C_});
    ck_tile::HostTensor<IndexDataType> h_out_index({N_, Ho_, Wo_, C_});
    ck_tile::HostTensor<IndexDataType> h_out_ref_index({N_, Ho_, Wo_, C_});

    // Initialize input with random data
    ck_tile::FillUniformDistribution<InDataType>{-5.f, 5.f}(h_in);
    h_out.SetZero();
    h_out_ref.SetZero();

    // Device memory
    ck_tile::DeviceMem d_in(h_in.get_element_space_size_in_bytes());
    ck_tile::DeviceMem d_out(h_out.get_element_space_size_in_bytes());
    ck_tile::DeviceMem d_out_index(h_out_index.get_element_space_size_in_bytes());

    d_in.ToDevice(h_in.data());
    d_out.SetZero();
    d_out_index.SetZero();

    // Build shapes and strides (NHWC layout)
    const auto input_shape      = ck_tile::make_tuple(N_, H_, W_, C_);
    const auto output_shape     = ck_tile::make_tuple(N_, Ho_, Wo_, C_);
    const auto input_strides    = ck_tile::make_tuple(H_ * W_ * C_, W_ * C_, C_, 1);
    const auto output_strides   = ck_tile::make_tuple(Ho_ * Wo_ * C_, Wo_ * C_, C_, 1);
    const auto window_lengths   = ck_tile::make_tuple(Y_, X_);
    const auto window_strides   = ck_tile::make_tuple(stride_h_, stride_w_);
    const auto window_dilations = ck_tile::make_tuple(dilation_h_, dilation_w_);
    const auto input_left_pads  = ck_tile::make_tuple(pad_h_left_, pad_w_left_);
    const auto input_right_pads = ck_tile::make_tuple(pad_h_right_, pad_w_right_);

    // Build host args for the generated kernel
    auto host_args = ck_tile::PoolHostArgs<decltype(input_shape), decltype(window_lengths)>{
        d_in.GetDeviceBuffer(),
        d_out.GetDeviceBuffer(),
        d_out_index.GetDeviceBuffer(),
        input_shape,
        output_shape,
        input_strides,
        output_strides,
        window_lengths,
        window_strides,
        window_dilations,
        input_left_pads,
        input_right_pads};

    // Stream config: no timing overhead for fastest execution
    ck_tile::stream_config stream_config{nullptr, false, 0, 0, 1, false, false, 1};

    // Launch generated kernel
    try
    {
        SelectedKernel::launch(host_args, stream_config);
    }
    catch(const std::exception& e)
    {
        std::string error_msg(e.what());
        if(error_msg.find("Arguments not supported") != std::string::npos)
        {
            GTEST_SKIP() << "Configuration not supported: " << e.what();
        }
        else
        {
            FAIL() << "Kernel launch failed: " << e.what();
        }
    }

    // Copy results back
    d_out.FromDevice(h_out.data());
    d_out_index.FromDevice(h_out_index.data());

    // Compute reference on host
    auto kernel_args_ref = ck_tile::PoolKernelArgs<decltype(input_shape), decltype(window_lengths)>{
        h_in.data(),
        h_out_ref.data(),
        h_out_ref_index.data(),
        input_shape,
        output_shape,
        input_strides,
        output_strides,
        window_lengths,
        window_strides,
        window_dilations,
        input_left_pads,
        input_right_pads};

    ck_tile::reference_pool2d<InDataType,
                              ComputeDataType,
                              OutDataType,
                              IndexDataType,
                              ReduceOpType,
                              decltype(input_shape),
                              decltype(window_lengths),
                              SelectedKernel::kOutputIndex>(
        h_in, h_out_ref, h_out_ref_index, kernel_args_ref, ReduceOpType{});

    // Verify value results
    bool pass_value = ck_tile::check_err(h_out, h_out_ref, "Error: Incorrect values!", 1e-5, 1e-5);
    EXPECT_TRUE(pass_value) << "Pooling value verification failed for " << KERNEL_NAME;

    // Verify index results if output_index is enabled
    if constexpr(SelectedKernel::kOutputIndex)
    {
        bool pass_index =
            ck_tile::check_err(h_out_index, h_out_ref_index, "Error: Incorrect indices!", 0, 0);
        EXPECT_TRUE(pass_index) << "Pooling index verification failed for " << KERNEL_NAME;
    }
}

TEST_P(PoolingTileEngineTest2D, KernelInfo)
{
    EXPECT_TRUE(strlen(KERNEL_NAME) > 0) << "Kernel name should not be empty";

    std::cout << "Testing kernel: " << KERNEL_NAME << std::endl;
    std::cout << "Problem size: N=" << N_ << " H=" << H_ << " W=" << W_ << " C=" << C_
              << " Window=" << Y_ << "x" << X_ << " Output=" << Ho_ << "x" << Wo_ << std::endl;
}

// Instantiate test suite with config-specific test parameters
// CONFIG_TEST_PARAMS is defined in the auto-generated test_params.hpp file
INSTANTIATE_TEST_SUITE_P(PoolingVerification,
                         PoolingTileEngineTest2D,
                         ::testing::ValuesIn(CONFIG_TEST_PARAMS),
                         [](const ::testing::TestParamInfo<PoolTestParams2D>& param_info) {
                             return "N" + std::to_string(param_info.param.N) + "_H" +
                                    std::to_string(param_info.param.H) + "_W" +
                                    std::to_string(param_info.param.W) + "_C" +
                                    std::to_string(param_info.param.C) + "_Y" +
                                    std::to_string(param_info.param.Y) + "_X" +
                                    std::to_string(param_info.param.X);
                         });
