def rocmnode(name) {
    return '(rocmtest || miopen) && (' + name + ')'
}

pipeline {
    agent none
    parameters {
        booleanParam(
            name: "FORCE_CI",
            defaultValue: false,
            description: "Force CI to run even when only non-relevant files are changed (default: OFF)")
    }
    stages{
        stage("Determine CI Execution") {
            agent{ label rocmnode("nogpu") }
            steps {
                script {
                    env.SHOULD_RUN_CI = String.valueOf(params.FORCE_CI.toBoolean())
                    echo "SHOULD_RUN_CI: ${env.SHOULD_RUN_CI}"
                }
            }
        }
    }
    post {
        success {
            script {
                withCredentials([string(credentialsId: 'ck_ci_errors_webhook_url', variable: 'WEBHOOK_URL')]) {
                    sh """
                        curl -X POST '${WEBHOOK_URL}' \
                        -H 'Content-Type: application/json' \
                        -d '{
                            "subject": "✅ Build Success - ${JOB_NAME}",
                            "text": "Build ${BUILD_NUMBER} completed successfully on branch ${BRANCH_NAME}"
                        }'
                    """
                }
            }
        }
        failure {
            withCredentials([string(credentialsId: 'ck_ci_errors_webhook_url', variable: 'WEBHOOK_URL')]) {
                    sh """
                        curl -X POST '${WEBHOOK_URL}' \
                        -H 'Content-Type: application/json' \
                        -d '{
                            "subject": "❌ Build Failed - ${JOB_NAME}",
                            "text": "Build ${BUILD_NUMBER} failed on branch ${BRANCH_NAME}"
                        }'
                    """
                }
        }
    }
}
