find_library(MSCCLPP_LIBRARY mscclpp HINTS /mscclpp/build)
if(NOT MSCCLPP_LIBRARY)
    message(FATAL_ERROR "MSCCLPP library not found in /mscclpp/build.")
endif()
find_path(MSCCLPP_INCLUDE_DIR mscclpp/core.hpp HINTS /mscclpp/include)
if(NOT MSCCLPP_INCLUDE_DIR)
    message(FATAL_ERROR "MSCCLPP include directory not found in /mscclpp/include.")
endif()
add_executable(example_cross_gpu_reduce cross_gpu_reduce.cpp)
target_include_directories(example_cross_gpu_reduce PRIVATE ${MSCCLPP_INCLUDE_DIR})
target_link_libraries(example_cross_gpu_reduce PRIVATE ${MSCCLPP_LIBRARY})