make -j 15                                                              \
            example_gemm_xdl_fp8_v3                                     \
            example_gemm_xdl_fp16_fp8_v3                                \
            example_gemm_xdl_fp8                                        \
            example_gemm_xdl_fp8_bf8                                    \
            example_gemm_xdl_fp16_fp8                                   \
            example_convnd_fwd_xdl_fp8                                  \
            example_convnd_fwd_xdl_bf8                                  \
            example_convnd_fwd_xdl_fp16_comp_fp8                        \
            example_convnd_fwd_xdl_fp8_bf8                              \
            example_convnd_fwd_xdl_bf8_fp8                              \
            example_grouped_gemm_xdl_fixed_nk_fp16_fp8                  \
            example_grouped_conv_bwd_weight_xdl_fp16_comp_bf8_fp8       \
            example_splitK_gemm_xdl_fp16_fp8                            \
            example_grouped_conv_bwd_data_xdl_fp16_comp_bf8_fp8         \
            elementwise_scale_permute_amax_2D_fp16_fp8                  \
            example_convnd_fwd_xdl_convinvscale_fp8                     \
            example_convnd_fwd_xdl_convscale_fp8                        \
            example_convnd_fwd_xdl_convscale_bf8                        \
            example_convnd_fwd_xdl_convscale_fp8_bf8                    \
            example_convnd_fwd_xdl_convscale_bf8_fp8                    \
            example_convnd_fwd_xdl_convscale_relu_fp8                   \
            example_convnd_fwd_xdl_convscale_add_fp8                    \
            example_convnd_fwd_xdl_convscale_relu_amax_fp8              \
            example_convnd_fwd_xdl_convscale_amax_fp8                   \
            example_gemm_multiply_multiply_xdl_fp8                      \
            example_gemm_multiply_multiply_xdl_fp8_ab_scale             \
            test_fp8                                                    \
            example_gemm_add_add_xdl_fp16                               \
            test_custom_type                                            \
            test_gemm_universal                                         \
            test_pool