jobs:
    -
        kernel_include_regex:
        kernel_exclude_regex:
        kernel_iteration_range: "[1, [3-4]]"
        output_file: out
        output_directory: ck_test
        output_format: [json, csv, otf2, pftrace]
        truncate_kernels: true
        sys_trace: true
        advanced_thread_trace: true
        att_library_path: /home/aghamari/rocm-tools/lib
        att_target_cu: 1
        att_shader_engine_mask: "0xf"
        att_simd_select: "0xf"
        att_buffer_size: "0x6000000"
