if(GPU_TARGETS MATCHES "gfx9|gfx11|gfx12")
    add_gtest_executable(test_ck_tile_reduce2d test_reduce2d.cpp)
    add_gtest_executable(test_ck_tile_multi_reduce2d_threadwise test_multi_reduce2d_threadwise.cpp)
    if(result EQUAL 0)
        target_link_libraries(test_ck_tile_reduce2d PRIVATE utility)
        target_link_libraries(test_ck_tile_multi_reduce2d_threadwise PRIVATE utility)
    endif()
endif()

# Multi-reduce tests require gfx940 or higher (MI300+)
# This is due to use of atomic add with fp16 type.
if(GPU_TARGETS MATCHES "gfx94[0-9]")
    add_gtest_executable(test_ck_tile_multi_reduce2d_multiblock test_multi_reduce2d_multiblock.cpp)
    if(result EQUAL 0)
        target_link_libraries(test_ck_tile_multi_reduce2d_multiblock PRIVATE utility)
    endif()
endif()
