# SPDX-License-Identifier: MIT
# Copyright (c) 2018-2025, Advanced Micro Devices, Inc. All rights reserved.
# generate kernel instances to speed up compilation

import copy
import fnmatch
import itertools
from collections import defaultdict
from dataclasses import asdict, dataclass, is_dataclass
from enum import Enum, auto
from pathlib import Path
from typing import Dict, List, Tuple

from codegen.cmake_config import GEN_DIR
from codegen.cpp_symbol_map import (
    BOOL_MAP,
    BWD_DTYPE_MAP,
    MODE_MAP,
    configure_file,
    cpp_value,
)
from codegen.utils import update_file


class CppEnum(Enum):
    def __str__(self):
        return f"{self.__class__.__name__}::{self.name}"


class CKTileEnum(Enum):
    def __str__(self):
        return f"ck_tile::{self.__class__.__name__}::{self.name}"


class fmha_bwd_kernel_kind(CppEnum):
    dot_do_o = (auto(),)
    dq_dk_dv = (auto(),)
    convert_dq = (auto(),)


class BlockAttentionBiasEnum(CKTileEnum):
    NO_BIAS = "nbias"
    ELEMENTWISE_BIAS = "bias"
    ALIBI = "alibi"


class CKTileTemplate:
    def __str__(self):
        assert is_dataclass(self)
        args = [cpp_value(a) for a in asdict(self).values()]
        return f"ck_tile::{self.__class__.__name__}<{', '.join(args)}>"


@dataclass(frozen=True)
class BlockDropoutBwd(CKTileTemplate):
    IsDropout: bool
    IsWG32: bool
    IsStoreRandval: bool

    @property
    def check(self) -> str:
        if not self.IsDropout:
            return "t.has_dropout == false"
        else:
            return f"t.has_dropout == true && t.is_store_randval == {cpp_value(self.IsStoreRandval)}"

    @property
    def id(self) -> str:
        if not self.IsDropout:
            return "ndropout"
        else:
            return f"dropout_{'wg32' if self.IsWG32 else 'wg16'}{'_store_randval' if self.IsStoreRandval else ''}"


DROPOUTS = [
    BlockDropoutBwd(False, True, False),
    BlockDropoutBwd(True, True, False),
    BlockDropoutBwd(True, True, True),
    BlockDropoutBwd(True, False, False),
    BlockDropoutBwd(True, False, True),
]


@dataclass(frozen=True)
class GenericAttentionMask(CKTileTemplate):
    IsMasking: bool = True
    IsLocal: bool = False

    @property
    def check(self) -> str:
        if not self.IsMasking:
            return "t.mask_type == mask_enum::no_mask"
        elif not self.IsLocal:
            return "t.mask_type == mask_enum::mask_top_left || t.mask_type == mask_enum::mask_bottom_right"
        else:
            return "t.mask_type == mask_enum::window_generic"

    @property
    def id(self) -> str:  # used for kernel name
        if not self.IsMasking:
            return "nmask"
        elif not self.IsLocal:
            return "mc"  # c for causal
        else:
            return "mg"  # g for generic


@dataclass(frozen=True)
class SimplifiedGenericAttentionMask(CKTileTemplate):
    IsMasking: bool = True

    @property
    def check(self) -> str:
        if self.IsMasking:
            return "t.mask_type != mask_enum::no_mask"
        else:
            return "t.mask_type == mask_enum::no_mask"

    @property
    def id(self) -> str:
        if self.IsMasking:
            return "mask"
        else:
            return "nmask"


def get_masks(mask: str):
    if mask == "generic":
        return [
            GenericAttentionMask(False),
            GenericAttentionMask(True, False),
            GenericAttentionMask(True, True),
        ]
    elif mask == "simplified":
        return [
            SimplifiedGenericAttentionMask(False),
            SimplifiedGenericAttentionMask(True),
        ]
    else:
        raise ValueError(f"Unknown mask type: {mask}")


FMHA_BWD_KERNEL_HEADER = """// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2024, Advanced Micro Devices, Inc. All rights reserved.\n
// auto generated by generate.py
#include "fmha_bwd.hpp"
"""

FMHA_BWD_API_FILENAME = "fmha_bwd_api.cpp"
FMHA_BWD_API = """

template <>
float fmha_bwd<2>(fmha_bwd_traits t, fmha_bwd_args a, const ck_tile::stream_config& s){{
    float r = -1;
{F_dispatch}
    return r;
}}
"""


def FMHA_BWD_API_COND_STATEMENT(F_cond: str, F_body: str, *, indent=0, if_=0) -> str:
    lines = [
        f"{'if' if if_ == 0 else 'else if'}({F_cond})",
        "{",
        *["    " + line for line in F_body.split("\n") if line.strip() != ""],
        "}",
    ]
    return "\n".join(" " * indent + line for line in lines) + "\n"


def FMHA_BWD_API_INNER_DISPATCH(**args) -> str:
    return """
{F_if}((t.is_group_mode == {F_mode}) && ({F_mask_check}) && (static_cast<int>(t.bias_type) == static_cast<int>({F_bias})) && (t.has_dbias == {F_dbias}) && ({F_dropout_check}) &&
        ({F_scheck}) && ({F_dcheck}) && ({F_dvcheck}) && (t.is_deterministic == {F_deterministic}){F_cond_extra}) {{
    if(s.log_level_ > 0)
        printf(", {F_name}");
    using trait_t = {F_trait};
    return FmhaBwdKernelGroup<trait_t, {F_kernel_kinds}>::run(s, a);
}}
""".format(**{k: cpp_value(v) for k, v in args.items()})


# M0 size for 1d kernels (dot/convert)
M0_1D = 64


@dataclass(frozen=True)
class FmhaBwdApiTrait:
    idx: int  # this is not a tunable, but a counter to differentiate symbol
    extra_cond: str  # extra condition to enable this trait
    # sync with fmha_bwd_traits<>, to generate fallback calls
    kernel_kinds: Tuple[fmha_bwd_kernel_kind, ...]
    dtype: str  # data type
    mode: str  # value from MODE_MAP
    FmhaMask: GenericAttentionMask | SimplifiedGenericAttentionMask
    BiasEnum: BlockAttentionBiasEnum
    kHasBiasGrad: bool
    FmhaDropout: BlockDropoutBwd
    kPadS1D: bool  # spad for 1d kernels (dot/convert)
    kPadD: bool
    kPadDv: bool
    kIsDeterministic: bool
    HDim: int
    kM0: int
    kN0: int
    MaxSeqLenQ: int
    kUseTrLoad: bool

    @property
    def bhdq(self) -> int:
        return self.HDim

    @property
    def bhdv(self) -> int:
        return self.HDim

    @property
    def kIsGroupMode(self) -> bool:
        return self.mode == "group"

    @property
    def DataType(self) -> str:
        return BWD_DTYPE_MAP[self.dtype]

    @property
    def scheck(self) -> str:
        if self.mode == "group":
            return "true"  # always support
        elif self.kPadS1D:
            return f"a.seqlen_q % {M0_1D} != 0"
        else:  # self.spad1d == 'f'
            return f"a.seqlen_q % {M0_1D} == 0"

    @property
    def dcheck(self) -> str:
        if self.kPadD:
            return f"a.hdim_q % {self.bhdq} != 0"
        else:
            return f"a.hdim_q % {self.bhdq} == 0"

    @property
    def dvcheck(self) -> str:
        if self.kPadDv:
            return f"a.hdim_v % {self.bhdv} != 0"
        else:
            return f"a.hdim_v % {self.bhdv} == 0"

    @property
    def convert_dq_kn0(self) -> int:
        return self.kN0 if self.kIsDeterministic else 0

    def kernel_name(self, k: fmha_bwd_kernel_kind) -> str:
        if k == fmha_bwd_kernel_kind.dot_do_o:
            pad = ""
            if self.kPadS1D:
                pad += "s"
            if self.kPadDv:
                pad += "dv"
            if pad != "":
                pad = f"p{pad}"
            else:
                pad = "npad"
            return f"fmha_bwd_{k.name}_d{self.HDim}_{self.dtype}_{self.mode}_{pad}"
        elif k == fmha_bwd_kernel_kind.dq_dk_dv:
            pad = ""
            if self.kPadD:
                pad += "d"
            if self.kPadDv:
                pad += "dv"
            if pad != "":
                pad = f"p{pad}"
            else:
                pad = "npad"

            n = f"fmha_bwd_{k.name}_d{self.HDim}_{self.dtype}_{self.mode}_{self.kM0}x{self.kN0}_{pad}"
            n += f"_{self.BiasEnum.value}"
            n += f"_dbias{int(self.kHasBiasGrad)}"
            n += f"_{self.FmhaMask.id}"
            n += f"_{self.FmhaDropout.id}"
            n += f"_deterministic{int(self.kIsDeterministic)}"
            n += f"_trload{int(self.kUseTrLoad)}"
            n += f"_maxq{self.MaxSeqLenQ}"
            return n
        elif k == fmha_bwd_kernel_kind.convert_dq:
            pad = ""
            if self.kPadS1D:
                pad += "s"
            if self.kPadD:
                pad += "d"
            if pad != "":
                pad = f"p{pad}"
            else:
                pad = "npad"

            n = f"fmha_bwd_{k.name}_d{self.HDim}_{self.dtype}_n{self.convert_dq_kn0}_{self.mode}_{pad}_deterministic{int(self.kIsDeterministic)}"
            return n
        else:
            raise ValueError(f"Unknown kernel kind: {k}")

    def kernel_impl(self, k: fmha_bwd_kernel_kind) -> str:
        kname = self.kernel_name(k)
        cpp_in = Path(__file__).parent.parent.parent / "fmha_bwd_kernel_impl.cpp.in"
        params = ()
        kvargs = {}
        if k == fmha_bwd_kernel_kind.dot_do_o:
            params = (
                "HDim",
                "DataType",
                "kIsGroupMode",
                "kPadS1D",
                "kPadDv",
            )
        elif k == fmha_bwd_kernel_kind.dq_dk_dv:
            params = (
                "HDim",
                "kM0",
                "kN0",
                "DataType",
                "FmhaMask",
                "FmhaDropout",
                "BiasEnum",
                "kIsGroupMode",
                "kHasBiasGrad",
                "kPadS1D",
                "kPadD",
                "kPadDv",
                "kIsDeterministic",
                "kUseTrLoad",
                "MaxSeqLenQ",
            )
        elif k == fmha_bwd_kernel_kind.convert_dq:
            params = (
                "HDim",
                "DataType",
                "kIsGroupMode",
                "kPadS1D",
                "kPadD",
                "kIsDeterministic",
            )
            kvargs = {"kN0": self.convert_dq_kn0}
        else:
            raise ValueError(f"Unknown kernel kind: {k}")
        return configure_file(cpp_in)(
            **{k: getattr(self, k) for k in params},
            **kvargs,
            KernelKind=k,
            KernelName=kname,
        )

    @property
    def group_traits_t(self) -> str:
        params = (
            "HDim",
            "kM0",
            "kN0",
            "DataType",
            "kIsGroupMode",
            "FmhaMask",
            "FmhaDropout",
            "BiasEnum",
            "kHasBiasGrad",
            "kPadS1D",
            "kPadD",
            "kPadDv",
            "kIsDeterministic",
            "kUseTrLoad",
            "MaxSeqLenQ",
        )
        return f"fmha_bwd_kernal_group_traits<{', '.join(cpp_value(getattr(self, k)) for k in params)}>"

    @property
    def id(self) -> str:
        pad = ""
        if self.kPadD:
            pad += "d"
        if self.kPadDv:
            pad += "dv"
        if self.kPadS1D:
            pad += "s1"
        if pad != "":
            pad = f"p{pad}"
        else:
            pad = "npad"

        n = f"fmha_bwd_d{self.HDim}_{self.dtype}_{self.mode}_{self.kM0}x{self.kN0}_{pad}"
        n += f"_{self.BiasEnum.value}"
        n += f"_dbias{int(self.kHasBiasGrad)}"
        n += f"_{self.FmhaMask.id}"
        n += f"_{self.FmhaDropout.id}"
        n += f"_deterministic{int(self.kIsDeterministic)}"
        n += f"_trload{int(self.kUseTrLoad)}"
        n += f"_maxq{self.MaxSeqLenQ}"
        return n


class FmhaBwdApiPool:
    def __init__(self):
        self.dq_dk_dv_pool = defaultdict(
            lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
        )

    def register_dq_dk_dv_traits(self, trait: FmhaBwdApiTrait) -> None:
        # TODO: do we need to check duplication?
        self.dq_dk_dv_pool[trait.kUseTrLoad][trait.MaxSeqLenQ][trait.dtype][
            trait.HDim
        ].append(copy.copy(trait))

    @staticmethod
    def if_(i: int) -> str:
        return "if" if i == 0 else "else if"

    def _api_innders(self, traits: List[FmhaBwdApiTrait]):
        inners = ""
        i = 0
        for trait in traits:
            inners += FMHA_BWD_API_INNER_DISPATCH(
                F_if=self.if_(i),
                F_name=trait.id,
                F_mode=MODE_MAP[trait.mode],
                F_mask_check=trait.FmhaMask.check,
                F_bias=trait.BiasEnum,
                F_dbias=BOOL_MAP[trait.kHasBiasGrad],
                F_dropout_check=trait.FmhaDropout.check,
                F_scheck=trait.scheck,
                F_dcheck=trait.dcheck,
                F_dvcheck=trait.dvcheck,
                F_deterministic=BOOL_MAP[trait.kIsDeterministic],
                F_trait=trait.group_traits_t,
                F_kernel_kinds=cpp_value(trait.kernel_kinds),
                F_cond_extra=trait.extra_cond,
            )
            i += 1
        return inners

    @staticmethod
    def trload_sort_key(tf: bool):
        return 0 if tf else 1  # sort 't' before 'f'

    @staticmethod
    def max_seq_q_sort_key(max_seq_q):
        return max_seq_q if max_seq_q != 0 else 1000000  # sort 0 to the end

    @staticmethod
    def max_seq_q_cond(max_seq_q: int) -> str:
        if max_seq_q == 0:
            return "true /* no seqlen_q limit */"
        else:
            return f"a.seqlen_q <= {max_seq_q}"

    @staticmethod
    def dtype_cond(dtype: str) -> str:
        return f't.data_type.compare("{dtype}") == 0'

    @staticmethod
    def hdim_cond(hdim: int) -> str:
        return f"t.hdim_q <= {hdim} && t.hdim_v <= {hdim}"

    @property
    def api(self) -> str:
        tr_load_cond_map = {
            True: "ck_tile::is_load_tr_supported()",
            False: "true /* no trload requirement */",
        }
        per_tr_load = ""
        for tr_load in sorted(self.dq_dk_dv_pool.keys(), key=self.trload_sort_key):
            per_max_seq_q = ""
            for max_seq_q in sorted(
                self.dq_dk_dv_pool[tr_load].keys(), key=self.max_seq_q_sort_key
            ):
                per_dtypes = ""
                dtype_cases = self.dq_dk_dv_pool[tr_load][max_seq_q]
                for j, dtype in enumerate(dtype_cases):
                    per_hdim_case = ""
                    hdim_cases = dtype_cases[dtype]
                    for k, hdim in enumerate(hdim_cases):
                        traits = hdim_cases[hdim]
                        inners = self._api_innders(traits)
                        per_hdim_case += FMHA_BWD_API_COND_STATEMENT(
                            if_=k, F_cond=self.hdim_cond(hdim), F_body=inners
                        )
                    per_dtypes += FMHA_BWD_API_COND_STATEMENT(
                        if_=j, F_cond=self.dtype_cond(dtype), F_body=per_hdim_case
                    )
                per_max_seq_q += FMHA_BWD_API_COND_STATEMENT(
                    F_cond=self.max_seq_q_cond(max_seq_q), F_body=per_dtypes
                )
            per_tr_load += FMHA_BWD_API_COND_STATEMENT(
                F_cond=tr_load_cond_map[tr_load], F_body=per_max_seq_q, indent=4
            )
        if not per_tr_load:
            # empty string we add some ignore to suppress warning in api
            per_tr_load += "    (void)t ; (void)s ; (void)a;"
        result = FMHA_BWD_KERNEL_HEADER + FMHA_BWD_API.format(F_dispatch=per_tr_load)
        return result.replace("\n\n", "\n")


def get_kernel_tiles(
    dtype: str, tr_load: bool
) -> Tuple[Tuple[Tuple[fmha_bwd_kernel_kind, ...], int, int, int, int, str], ...]:
    "hdim, bm0, bn0, max_seq_q, extra_cond"
    if dtype == "fp16" or dtype == "bf16":
        kernels3 = (
            fmha_bwd_kernel_kind.dot_do_o,
            fmha_bwd_kernel_kind.dq_dk_dv,
            fmha_bwd_kernel_kind.convert_dq,
        )
        kernels2 = (fmha_bwd_kernel_kind.dot_do_o, fmha_bwd_kernel_kind.dq_dk_dv)
        if not tr_load:
            return (
                (kernels3, 32, 32, 128, 0, ""),
                (kernels3, 64, 32, 128, 0, ""),
                (kernels3, 128, 16, 128, 0, ""),
                (kernels3, 256, 16, 64, 0, ""),
            )
        else:
            return (
                (kernels3, 128, 32, 128, 0, " && (a.seqlen_k <= 256)"),
                (kernels3, 128, 16, 192, 0, ""),
                (kernels2, 128, 16, 16, 16, ""),
            )
    else:
        return ()


def get_bwd_blobs(
    filter: str, receipt, mask_impl, optdim_list
) -> Tuple[FmhaBwdApiPool, Dict[str, str]]:
    if filter == "":
        filter = "*"
    # use dict as ordered set
    kernels: Dict[str, str] = {}
    api_pool = FmhaBwdApiPool()
    bool_values = [False, True]

    for dtype, tr_load in itertools.product(BWD_DTYPE_MAP.keys(), bool_values):
        tiles = get_kernel_tiles(dtype, tr_load)
        bools = itertools.product(*([bool_values] * 5))
        for (
            (kernel_kinds, hdim, bm0, bn0, max_seq_q, extra_cond),
            mode,
            mask,
            dropout,
            bias,
            (dbias, spad1d, dpad, dvpad, deterministic),
        ) in itertools.product(
            tiles,
            MODE_MAP.keys(),
            get_masks(mask_impl),
            DROPOUTS,
            list(BlockAttentionBiasEnum),
            bools,
        ):
            if (optdim_list != [-1]) and (hdim not in optdim_list):
                continue

            if (mode == "group") and (spad1d):
                continue
            if (mode == "group" or mask.IsMasking) and max_seq_q != 0:
                continue
            if dbias and (bias != BlockAttentionBiasEnum.ELEMENTWISE_BIAS):
                continue
            if dropout.IsDropout and dropout.IsWG32:
                continue
            if tr_load and (dpad or dvpad):
                continue  # tr_load cannot work with dpad or dvpad
            t = FmhaBwdApiTrait(
                kernel_kinds=kernel_kinds,
                idx=0,
                extra_cond=extra_cond,
                dtype=dtype,
                mode=mode,
                FmhaMask=mask,
                BiasEnum=bias,
                kHasBiasGrad=dbias,
                FmhaDropout=dropout,
                kPadS1D=spad1d,
                kPadD=dpad,
                kPadDv=dvpad,
                kIsDeterministic=deterministic,
                kUseTrLoad=tr_load,
                HDim=hdim,
                kM0=bm0,
                kN0=bn0,
                MaxSeqLenQ=max_seq_q,
            )

            if not fnmatch.fnmatch(t.id, filter):
                continue

            # Flash attention integration
            NO_BIAS = BlockAttentionBiasEnum.NO_BIAS
            ALIBI = BlockAttentionBiasEnum.ALIBI
            ELEMENTWISE_BIAS = BlockAttentionBiasEnum.ELEMENTWISE_BIAS
            if receipt == 2:
                cond = dtype in ["fp16", "bf16"]
                cond &= bias in [NO_BIAS, ALIBI]
                cond &= not dropout.IsDropout or not dropout.IsStoreRandval
                cond &= dpad == dvpad
                if not cond:
                    continue
            elif receipt == 3:
                cond = dtype in ["fp16", "bf16"]
                cond &= bias in [NO_BIAS, ALIBI]
                cond &= dpad == dvpad
                cond &= not deterministic
                if not cond:
                    continue
            # PyTorch integration
            elif receipt == 4:
                cond = dtype in ["fp16", "bf16"]
                cond &= bias in [NO_BIAS, ELEMENTWISE_BIAS]
                cond &= not dropout.IsDropout or not dropout.IsStoreRandval
                cond &= dpad == dvpad
                cond &= not deterministic
                if not cond:
                    continue
            # Aiter (mha_bwd) integration
            elif receipt == 300:
                cond = dtype in ["fp16", "bf16"]
                cond &= mode == "batch"
                cond &= not dropout.IsDropout or not dropout.IsStoreRandval
                if not cond:
                    continue
            # Aiter (mha_varlen_bwd) integration
            elif receipt == 400:
                cond = dtype in ["fp16", "bf16"]
                cond &= mode == "group"
                cond &= not dropout.IsDropout or not dropout.IsStoreRandval
                if not cond:
                    continue
            # aiter::mha_bwd C++ api integration
            elif receipt == 600:
                cond = dtype in ["fp16", "bf16"]
                if not cond:
                    continue
            for k in t.kernel_kinds:
                kernels[t.kernel_name(k)] = t.kernel_impl(k)
            api_pool.register_dq_dk_dv_traits(t)

    return api_pool, kernels


def make_shards(kernels: Dict[str, str], num_shards: int) -> Dict[str, str]:
    """Combine kernels into shards."""
    if len(kernels) <= num_shards or num_shards <= 0:
        return kernels  # no sharding

    k_names = list(kernels.keys())
    k_names.sort()

    shards = {
        f"fmha_bwd_kernels_shard_{i:03d}": "// Shard {i:03d} contains:\n"
        + "\n".join("// " + n for i, n in enumerate(k_names) if (i % num_shards) == i)
        + "\n"
        + "\n".join(
            f"// start {k_names[j]}:\n{kernels[k_names[j]]}\n// end {k_names[j]}\n"
            for j in range(len(kernels))
            if (j % num_shards) == i
        )
        for i in range(num_shards)
    }
    return shards


def write_blobs(
    output_dir: Path, filter: str, receipt, optdim_list, mask_impl, num_shards=0
) -> None:
    api_pool, kernels = get_bwd_blobs(filter, receipt, mask_impl, optdim_list)
    kernels = make_shards(kernels, num_shards)
    update_file(output_dir / FMHA_BWD_API_FILENAME, api_pool.api)
    for name, code in kernels.items():
        update_file(output_dir / (name + ".cpp"), code)


def list_blobs(
    file_path: Path, filter: str, receipt, optdim_list, mask_impl, num_shards=0
) -> None:
    _, kernels = get_bwd_blobs(filter, receipt, mask_impl, optdim_list)
    kernels = make_shards(kernels, num_shards)
    with file_path.open("a") as f:
        f.write(str(file_path.parent / GEN_DIR / FMHA_BWD_API_FILENAME) + "\n")
        for name, _ in kernels.items():
            f.write(str(file_path.parent / GEN_DIR / (name + ".cpp")) + "\n")
