# Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT
# generate kernel instances to speed up compilation
import copy
import fnmatch
import itertools
import json
import os
from collections import OrderedDict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, ClassVar, Dict, Iterable, List, Optional, Tuple

from codegen.arch import ArchTrait, get_factories_for_targets
from codegen.cmake_config import GEN_DIR
from codegen.cpp_symbol_map import (
    LAYOUT_MAP,
    BIAS_CHECK_MAP,
    BOOL_MAP,
    PIPELINE_MAP,
    PIPELINE_ENUM_MAP,
    MODE_MAP,
    FWD_DTYPE_MAP,
    BIAS_MAP,
    get_mask_map,
    get_mask_cpp_type,
    get_mask_cpp_check_expr,
    QSCALE_CHECK_MAP,
    QSCALE_MAP,
)
from codegen.utils import check_duplicates_and_paddings, if_, indent, update_file


DTYPE_BITS = {
    "fp32": 32,
    "fp16": 16,
    "bf16": 16,
    "fp8": 8,
    "fp8bf16": 8,
    "fp8fp32": 8,
    "bf8": 8,
    "mxfp8": 8,
    "mxfp4": 4,
}

K0_MAX_SUBMAX_MAP = {
    32: 32,
    48: 48,
    64: 64,
    80: 96,
    96: 128,
    128: 128,
    192: 192,
    256: 256,
}

FMHA_FWD_KERNEL_HEADER = """// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2025, Advanced Micro Devices, Inc. All rights reserved.\n
// auto generated by generate.py
#include "ck_tile/ops/fmha/block/variants.hpp"
#include "fmha_fwd.hpp"
"""

FMHA_FWD_KERNEL_HEADER_QR_HPAD = """// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2025, Advanced Micro Devices, Inc. All rights reserved.\n
// auto generated by generate.py
#if defined(__HIP_DEVICE_COMPILE__) && \
    (defined(__gfx1100__) || defined(__gfx1101__) || defined(__gfx1102__) || \
     defined(__gfx1103__) || defined(__gfx1150__) || defined(__gfx1151__) || \
     defined(__gfx1152__) || defined(__gfx1153__) || defined(__gfx11_generic__) || \
     defined(__gfx1200__) || defined(__gfx1201__) || defined(__gfx12_generic__))
#if !defined(CK_TILE_EXPERIMENTAL_USE_BUFFER_LOAD_OOB_CHECK_OFFSET_TRICK)
#define CK_TILE_EXPERIMENTAL_USE_BUFFER_LOAD_OOB_CHECK_OFFSET_TRICK 1
#endif
#endif
#include "ck_tile/ops/fmha/block/variants.hpp"
#include "fmha_fwd.hpp"
"""

FMHA_FWD_KERNEL_BODY_TEMPLATE = """
#include <iostream>

#if !defined(__HIP_DEVICE_COMPILE__) || ({F_arch.preprocessor_check})

using fmha_dtype = {F_dtype};

using fmha_block_tile = ck_tile::sequence<{F_bm0}, {F_bn0}, {F_bk0}, {F_bn1}, {F_bk1}, {F_bk0max}>;

using fmha_shape = ck_tile::TileFmhaShape<fmha_block_tile,
                                          ck_tile::sequence<{F_rm0}, {F_rn0}, {F_rk0}>,
                                          ck_tile::sequence<{F_wm0}, {F_wn0}, {F_wk0}>,
                                          ck_tile::sequence<{F_rm1}, {F_rn1}, {F_rk1}>,
                                          ck_tile::sequence<{F_wm1}, {F_wn1}, {F_wk1}>,
                                          {F_vlayout}>;

using fmha_traits = ck_tile::TileFmhaTraits<{F_spad},
                                            {F_skpad},
                                            {F_dpad},
                                            {F_dvpad},
                                            {F_logits},
                                            {F_bias},
                                            false,
                                            {F_lse},
                                            {F_dropout},
                                            {F_qscale},
                                            {F_occupancy},
                                            {F_skip},
                                            {F_sink}>;

using fmha_variant = ck_tile::ComposedAttention<{F_logits} * ck_tile::LOGITS_SOFT_CAP, CK_TILE_FMHA_FWD_FAST_EXP2>;

using fmha_mask = {F_mask};

using fmha_pipeline_problem = ck_tile::BlockFmhaPipelineProblem<
    typename FmhaFwdTypeConfig<fmha_dtype>::QDataType,
    typename FmhaFwdTypeConfig<fmha_dtype>::KDataType,
    typename FmhaFwdTypeConfig<fmha_dtype>::VDataType,
    typename FmhaFwdTypeConfig<fmha_dtype>::SaccDataType,
    typename FmhaFwdTypeConfig<fmha_dtype>::SMPLComputeDataType,
    typename FmhaFwdTypeConfig<fmha_dtype>::BiasDataType,
    typename FmhaFwdTypeConfig<fmha_dtype>::RandValOutputDataType,
    typename FmhaFwdTypeConfig<fmha_dtype>::LSEDataType,
    typename FmhaFwdTypeConfig<fmha_dtype>::PDataType,
    typename FmhaFwdTypeConfig<fmha_dtype>::OaccDataType,
    typename FmhaFwdTypeConfig<fmha_dtype>::ODataType,
    fmha_shape,
    {F_mode},
    fmha_variant,
    fmha_mask,
    {F_trload},
    fmha_traits>;

using fmha_pipeline = {F_pipeline}<
    fmha_pipeline_problem>;

using fmha_epilogue =
    ck_tile::Default2DEpilogue<ck_tile::Default2DEpilogueProblem<typename FmhaFwdTypeConfig<fmha_dtype>::OaccDataType,
                               typename FmhaFwdTypeConfig<fmha_dtype>::ODataType,
                               {F_spad}, {F_dvpad}>>;

using fmha_kernel = {F_kernel}<fmha_pipeline, fmha_epilogue>;


using trait = fmha_fwd_traits_<{F_hdim}, {F_dtype}, {F_mode},{F_bm0}, {F_bn0}, {F_bk0}, {F_bn1}, {F_bk1}, {F_bk0max}, {F_vlayout},
                        {F_pipeline_enum}, {F_logits}, fmha_mask, {F_bias}, {F_lse}, {F_dropout}, {F_qscale}, {F_spad}, {F_skpad}, {F_dpad}, {F_dvpad}, {F_trload}, {F_skip}, {F_sink}, {F_occupancy}>;

template<>
float fmha_fwd_<trait, {F_arch.tag}>(const ck_tile::stream_config& s, fmha_fwd_args a)
{{
    using k_ = fmha_kernel;
    if(a.selected_kernel_name != nullptr)
        *a.selected_kernel_name = "{F_kname}";
    if(s.log_level_ > 0)
        std::cout << ", {F_kname}" << std::flush;
    auto [kargs, grids] = {F_kargs_creator}<k_>(a);
    if(!k_::IsSupportedArgument(kargs))
    {{
        ck_tile::CK_TILE_ERROR("Arguments not supported! Skipping fmha_fwd!");
        return -1;
    }}
    const dim3 blocks                      = k_::BlockSize();
    constexpr ck_tile::index_t kBlockPerCu = k_::kBlockPerCu;
    return ck_tile::launch_kernel(s, ck_tile::make_kernel<kBlockPerCu, {F_arch.tag}>(k_{{}}, grids, blocks, 0, kargs));
}}

#endif // !defined(__HIP_DEVICE_COMPILE__) || ({F_arch.preprocessor_check})
"""

FMHA_FWD_KVSCALE_ALIGN_TEMPLATE = """
#if !defined(__HIP_DEVICE_COMPILE__) || ({F_arch.preprocessor_check})

template<>
ck_tile::index_t fmha_fwd_kvscale_align_<trait, {F_arch.tag}>()
{{
    return fmha_pipeline::kKVScaleAlign;
}}

#endif // !defined(__HIP_DEVICE_COMPILE__) || ({F_arch.preprocessor_check})
"""

FMHA_FWD_API_FILENAME = "fmha_fwd_api.cpp"
FMHA_FWD_API_HEADER = """
// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2025, Advanced Micro Devices, Inc. All rights reserved.\n
// auto generated by generate.py
#include <cstdio>
#include <cstdlib>
#include <string>

#include <hip/hip_runtime.h>

#include "fmha_fwd.hpp"

namespace {
bool get_num_cus(unsigned& num_cus) {
    int device;
    auto status = hipGetDevice(&device);
    if(status != hipSuccess) {
        fprintf(stderr, "failed to get device");
        return false;
    }

    hipDeviceProp_t props{};
    status = hipGetDeviceProperties(&props, device);
    if(status != hipSuccess) {
        fprintf(stderr, "failed to get device properties");
        return false;
    }

    num_cus = props.multiProcessorCount;
    return true;
}

unsigned get_num_thread_blocks(unsigned batch, unsigned nheads, unsigned max_seqlen_q, unsigned kM0) {
    const unsigned num_m_blocks = (max_seqlen_q + kM0 - 1) / kM0;
    const unsigned num_n_blocks = 1; // we assume that num_n_blocks is always 1

    return batch * nheads * num_m_blocks * num_n_blocks;
}
} // namespace
"""
FMHA_FWD_API_FUNC_TEMPLATE = """
namespace {{
float {F_func_name}([[maybe_unused]] fmha_fwd_traits t, [[maybe_unused]] fmha_fwd_args a, [[maybe_unused]] const ck_tile::stream_config& s) {{
    float r = -1;

    [[maybe_unused]] const float min_cu_util_rate = 0.8; // minimum CU utilization rate

    unsigned num_cus;
    if(!get_num_cus(num_cus)) {{
        return r;
    }}

    [[maybe_unused]] auto get_num_blocks = [&](unsigned kM0) {{
        return get_num_thread_blocks(a.batch, a.nhead_q, a.max_seqlen_q, kM0);
    }};

    [[maybe_unused]] const std::string device_name = ck_tile::get_device_name();

{F_dispatch}
    return r;
}}
}} // namespace
"""
FMHA_FWD_API_FOOTER = """
float fmha_fwd(fmha_fwd_traits traits, fmha_fwd_args args, const ck_tile::stream_config& config) {
    if (args.max_seqlen_q > 1) {
        float r = fmha_fwd_v3(traits, args, config);
        if (r >= 0) return r;
    }
    return fmha_fwd_v2(traits, args, config);
}
"""

FMHA_FWD_API_PER_ARCH = """{F_if}({F_arch.device_name_check}) {{
{F_dtype_case}
}}
"""

FMHA_FWD_API_PER_DTYPE = """{F_if}(t.data_type.compare(\"{F_dtype}\") == 0) {{
{F_hdim_case}
}}
"""

FMHA_FWD_API_PER_HDIM_CASE = """{F_if}(t.hdim_q <= {F_hdim} && t.hdim_v <= {F_hdim_v}) {{
{F_inner_dispatch}
}}
"""

FMHA_FWD_TRAIT_TYPE = """fmha_fwd_traits_<{F_hdim}, {F_dtype}, {F_mode}, {F_bm0}, {F_bn0}, {F_bk0}, {F_bn1}, {F_bk1}, {F_bk0max}, {F_vlayout}, {F_pipeline_enum}, {F_logits}, {F_mask}, {F_bias}, {F_lse}, {F_dropout}, {F_qscale}, {F_spad}, {F_skpad}, {F_dpad}, {F_dvpad}, {F_trload}, {F_skip}, {F_sink}, {F_occupancy}>"""

FMHA_FWD_API_INNER_DISPATCH = """{F_if}((t.is_group_mode == {F_mode}) && (t.is_v_rowmajor == {F_vlayout}) && (t.has_logits_soft_cap == {F_logits}) && ({F_mask_check}) && (t.bias_type == {F_bias_check}) && (t.has_lse == {F_lse})  && (t.has_dropout == {F_dropout}) && (t.qscale_type == {F_qscale_check}) && (t.skip_min_seqlen_q == {F_skip}) &&(t.has_sink == {F_sink}) &&
        ({F_scheck}) && ({F_seqtune}) && ({F_skcheck}) && ({F_dcheck}) && ({F_dvcheck}) && ({F_constraint})) {{
    using trait_ = {F_trait_type};
    return fmha_fwd_<trait_, {F_arch.tag}>(s, a);
}}
"""

FMHA_FWD_API_KVSCALE_TEMPLATE = """
ck_tile::index_t fmha_fwd_block_scale_size_kv([[maybe_unused]] const std::string& data_type, [[maybe_unused]] ck_tile::index_t hdim_q, [[maybe_unused]] ck_tile::index_t hdim_v) {{
{F_lookup}    return fmha_fwd_largest_n_tile_size;
}}
"""

FMHA_FWD_API_KVSCALE_LOOKUP = """    struct row {{ const char* arch; const char* data_type; ck_tile::index_t hdim_q, hdim_v, align; }};
    static const row table[] = {{
{F_rows}    }};

    const std::string device_name = ck_tile::get_device_name();
    for(const row& r : table)
        if(device_name.rfind(r.arch, 0) == 0 && data_type == r.data_type && hdim_q <= r.hdim_q && hdim_v <= r.hdim_v)
            return r.align;

"""

FMHA_FWD_API_KVSCALE_ROW = """        {{"{F_arch.name}", "{F_dtype_name}", {F_hdim}, {F_hdim_v}, fmha_fwd_kvscale_align_<{F_trait_type}, {F_arch.tag}>()}},
"""


@dataclass
class CppConstraint:
    bool_expr: str = None

    def __str__(self):
        if self.bool_expr is None:
            return "true"
        else:
            return f"{self.bool_expr}"

    def __and__(self, other):
        return CppConstraint(f"({str(self)}) && ({str(other)})")


@dataclass
class FmhaFwdApiTrait:
    arch: ArchTrait
    pipeline_tag: str
    # sync with fmha_fwd_traits<>, to generate fallback calls
    hdim: str
    dtype: str  # data type
    mode: str  # value from MODE_MAP
    bm0: int  # tile size along q seqlen (block size)
    bn0: int  # tile size along qk seqlen
    bk0: int  # tile size along qk gemm unroll
    bn1: int  # tile size along v head_dim
    bk1: int  # tile size along kv gemm unroll
    bk0max: int
    vlayout: str
    logits: str
    mask: str
    bias: str  #
    lse: str  #
    dropout: str
    qscale: str  #
    spad: str
    skpad: str
    dpad: str
    dvpad: str
    skip: str
    tr_load: str
    sink: str
    # Metadata-only hint mapped onto fmha_fwd_traits_::kOccupancy. Its sole
    # purpose here is to make otherwise-identical traits produce DISTINCT
    # template instantiations of `fmha_fwd_<traits, arch>`, so multiple
    # occupancy variants for the same tile can coexist in one shared object.
    occupancy: int = -1
    constraint: CppConstraint = field(default_factory=lambda: CppConstraint())

    @property
    def name(self) -> str:
        return (
            f"{self.hdim}-{self.dtype}-{self.mode}-{self.bm0}-{self.bn0}-{self.bk0}-{self.bn0}-{self.bk1}-{self.bk0max}-"
            + f"{self.vlayout}-{self.logits}-{self.mask}-{self.bias}-{self.lse}-{self.dropout}-{self.qscale}-{self.spad}-{self.skpad}-{self.dpad}-{self.dvpad}-{self.skip}-{self.sink}"
        )

    @property
    def scheck(self) -> str:
        if self.mode == "group":
            return "true/*group mode spad always true*/"  # group mode only generate spad/skpad == true
        if self.pipeline_tag in ["qr_async", "qr_async_trload", "qr_async_trload_v3", "qr_tdm"]:
            if self.spad == "t":
                return "true"  # always support
            else:
                return "true"
        elif self.pipeline_tag in ["qr", "qr_hpad", "qs"]:
            if self.spad == "t":
                return f"true /*a.seqlen_q % {self.bm0} != 0*/"  # TODO: order of get_pipelines() matters! (ugly)
            else:
                return f"a.seqlen_q % {self.bm0} == 0"
        else:
            assert False

    def seqtune(self, max_bm0: int) -> str:
        if self.bm0 == max_bm0 or self.bm0 == 64:
            return "true/*fall back to largest tile*/"
        else:
            if self.mode == "group":
                return f"a.max_seqlen_q <= {self.bm0}"
            return f"a.seqlen_q <= {self.bm0}"

    @property
    def skcheck(self) -> str:
        if self.mode == "group":
            return "true/*group mode skpad always true*/"  # group mode only generate spad/skpad == true
        if self.pipeline_tag == "qr_async":
            if self.skpad == "t":
                return f"(a.cu_seqlen_k_ptr != nullptr) || (a.seqlen_k == 0 || a.seqlen_k % {self.bn0} != 0)"
            else:
                return f"(a.cu_seqlen_k_ptr == nullptr) && (a.seqlen_k != 0 && a.seqlen_k % {self.bn0} == 0)"
        elif self.pipeline_tag in ["qr", "qr_hpad", "qs"]:
            if self.skpad == "t":
                return f"true /*a.seqlen_k % {self.bn0} != 0*/"  # TODO: order of get_pipelines() matters! (ugly)
            else:
                return f"(a.cu_seqlen_k_ptr == nullptr) && (a.seqlen_k != 0 && a.seqlen_k % {self.bn0} == 0)"
        elif self.pipeline_tag == "qr_tdm":
            if self.skpad == "t":
                return "true"
            else:
                return f"(a.cu_seqlen_k_ptr == nullptr) && (a.seqlen_k != 0 && a.seqlen_k % {self.bn0} == 0)"
        elif self.pipeline_tag in ["qr_async_trload", "qr_async_trload_v3"]:
            if self.skpad == "t":
                return "true"
            else:
                return "true"
        else:
            assert False

    @property
    def dcheck(self) -> str:
        if self.pipeline_tag == "qr_hpad":
            if self.dpad == "t":
                return "a.hdim_q % 8 == 0"
            else:
                assert False
        elif self.pipeline_tag == "qr_tdm":
            if self.dpad == "t":
                return "a.hdim_q % 8 == 0"
            return f"a.hdim_q % {K0_MAX_SUBMAX_MAP[self.bk0max]} == 0"
        elif self.pipeline_tag in ["qr", "qs", "qr_async", "qr_async_trload", "qr_async_trload_v3"]:
            bk0submax = K0_MAX_SUBMAX_MAP[self.bk0max]
            if self.dpad == "t":
                return f"true /*a.hdim_q % {bk0submax} != 0*/"  # TODO: order of get_pipelines() matters! (ugly)
            else:
                return f"a.hdim_q % {bk0submax} == 0"
        else:
            assert False

    @property
    def dvcheck(self) -> str:
        if self.pipeline_tag == "qr_hpad":
            if self.dvpad == "t":
                return "a.hdim_v % 8 == 0"
            else:
                assert False
        elif self.pipeline_tag == "qr_tdm":
            if self.dvpad == "t":
                return "a.hdim_v % 8 == 0"
            return f"a.hdim_v % {K0_MAX_SUBMAX_MAP[self.bk0max]} == 0"
        elif self.pipeline_tag in ["qr", "qs", "qr_async", "qr_async_trload", "qr_async_trload_v3"]:
            bk0submax = K0_MAX_SUBMAX_MAP[self.bk0max]
            if self.dvpad == "t":
                return f"true /*a.hdim_v % {bk0submax} != 0*/"  # TODO: order of get_pipelines() matters! (ugly)
            else:
                return f"a.hdim_v % {bk0submax} == 0"
        else:
            assert False


@dataclass
class FmhaFwdPipeline:
    tag: str

    F_vlayout: str  # row/col
    F_spad: str  # true/false
    F_skpad: str  #
    F_dpad: str  #
    F_dvpad: str  #
    F_logits: str  # t/f
    F_bias: str  # true/false
    F_lse: str  #
    F_dropout: str  #
    F_qscale: str  # no/pertensor
    F_mask: str  # value from MASK_MAP
    F_skip: str  # true/false
    F_trload: str  # true/false
    F_sink: str  # true/false
    F_constraint: CppConstraint = field(default_factory=lambda: CppConstraint())

    @property
    def name(self) -> str:
        def pad_name() -> str:
            n = ""
            if self.F_spad == "t":
                n += "s"
            if self.F_skpad == "t":
                n += "sk"
            if self.F_dpad == "t":
                n += "d"
            if self.F_dvpad == "t":
                n += "dv"
            if n != "":
                n = "p" + n
            return n

        pn = pad_name()
        n = f"{self.tag}_v{self.F_vlayout[0]}"
        if pn != "":
            n += f"_{pn}"
        else:
            n += "_npad"

        if self.F_logits == "t":
            n += "_logits"
        else:
            n += "_nlogits"

        if self.F_bias != "no":
            n += f"_{self.F_bias}"
        else:
            n += "_nbias"

        if self.F_mask[0:2] == "s_":
            if self.F_mask == "s_mask":
                n += "_mask"
            else:
                n += "_nmask"
        else:
            if self.F_mask != "no":
                n += f"_m{self.F_mask[0]}"
            else:
                n += "_nmask"

        if self.F_lse == "t":
            n += "_lse"
        else:
            n += "_nlse"

        if self.F_dropout == "t":
            n += "_dropout"
        else:
            n += "_ndropout"

        if self.F_skip == "t":
            n += "_skip"
        else:
            n += "_nskip"

        if self.F_qscale != "no":
            n += f"_{self.F_qscale}"
        else:
            n += "_nqscale"

        if self.F_trload == "t":
            n += "_trload"
        else:
            n += "_ntrload"
        if self.F_sink == "t":
            n += "_sink"
        else:
            n += "_nsink"

        return n


def api_trait_fmt_args(arch, dtype, hdim, trait: FmhaFwdApiTrait, max_bm0: int) -> dict:
    """Substitutions shared by every template that names a generated instance."""
    return dict(
        F_arch=arch,
        F_mode=MODE_MAP[trait.mode],
        F_vlayout=LAYOUT_MAP[trait.vlayout],
        F_pipeline_enum=PIPELINE_ENUM_MAP[trait.pipeline_tag],
        F_logits=BOOL_MAP[trait.logits],
        F_mask=get_mask_cpp_type(trait.mask),
        F_mask_check=get_mask_cpp_check_expr(trait.mask),
        F_bias_check=BIAS_CHECK_MAP[trait.bias],
        F_bias=BIAS_MAP[trait.bias],
        F_lse=BOOL_MAP[trait.lse],
        F_dropout=BOOL_MAP[trait.dropout],
        F_skip=BOOL_MAP[trait.skip],
        F_trload=BOOL_MAP[trait.tr_load],
        F_qscale_check=QSCALE_CHECK_MAP[trait.qscale],
        F_qscale=QSCALE_MAP[trait.qscale],
        F_sink=BOOL_MAP[trait.sink],
        F_scheck=trait.scheck,
        F_seqtune=trait.seqtune(max_bm0),
        F_skcheck=trait.skcheck,
        F_dcheck=trait.dcheck,
        F_dvcheck=trait.dvcheck,
        F_constraint=trait.constraint,
        F_spad=BOOL_MAP[trait.spad],
        F_skpad=BOOL_MAP[trait.skpad],
        F_dpad=BOOL_MAP[trait.dpad],
        F_dvpad=BOOL_MAP[trait.dvpad],
        F_bm0=trait.bm0,
        F_bn0=trait.bn0,
        F_bk0=trait.bk0,
        F_bn1=trait.bn1,
        F_bk1=trait.bk1,
        F_bk0max=trait.bk0max,
        F_occupancy=trait.occupancy,
        F_hdim=hdim,
        F_dtype=FWD_DTYPE_MAP[dtype],
    )


KVSCALE_ALIGN_PIPELINE_TAGS = ("qr_tdm",)


def emits_kvscale_align(pipeline_tag: str, qscale: str) -> bool:
    return pipeline_tag in KVSCALE_ALIGN_PIPELINE_TAGS and qscale == "blockscale"


class FmhaFwdApiPool:
    def __init__(self):
        self.pool = OrderedDict()

    def register_traits(self, trait: FmhaFwdApiTrait) -> None:
        hdim = trait.hdim, trait.bn1
        ts = (
            self.pool.setdefault(trait.arch, OrderedDict())
            .setdefault(trait.dtype, OrderedDict())
            .setdefault(hdim, [])
        )
        check_duplicates_and_paddings(ts, trait)
        ts.append(copy.copy(trait))

    def get_num_traits(
        self, filter_fn: Optional[Callable[[FmhaFwdApiTrait], bool]] = None
    ) -> int:
        if filter_fn is None:

            def accept_all(trait: FmhaFwdApiTrait) -> bool:
                return True

            filter_fn = accept_all

        return sum(
            sum(1 for trait in pool_by_hdim if filter_fn(trait))
            for pool_by_arch in self.pool.values()
            for pool_by_dtype in pool_by_arch.values()
            for pool_by_hdim in pool_by_dtype.values()
        )

    def render(
        self, func_name, filter_fn: Optional[Callable[[FmhaFwdApiTrait], bool]] = None
    ) -> str:
        if filter_fn is None:

            def accept_all(trait: FmhaFwdApiTrait) -> bool:
                return True

            filter_fn = accept_all

        def has_traits(node) -> bool:
            """Recursively traverse nested OrderedDicts and lists to determine if any FmhaFwdApiTrait satisfies filter_fn()."""
            if isinstance(node, list):
                return any(filter_fn(elem) for elem in node)
            elif isinstance(node, OrderedDict):
                return any(has_traits(val) for val in node.values())
            return False

        per_arch = str()
        for i_arch, (arch, pool_by_arch) in enumerate(
            item for item in self.pool.items() if has_traits(item[1])
        ):
            per_dtypes = str()
            for i_dtype, (dtype, pool_by_dtype) in enumerate(
                item for item in pool_by_arch.items() if has_traits(item[1])
            ):
                per_hdim_case = str()
                for i_hdim, ((hdim, hdim_v), pool_by_hdim) in enumerate(
                    item for item in pool_by_dtype.items() if has_traits(item[1])
                ):
                    max_bm0 = max(
                        (t.bm0 for t in pool_by_hdim if filter_fn(t)), default=0
                    )
                    inners = str()
                    for i_trait, trait in enumerate(
                        [trait for trait in pool_by_hdim if filter_fn(trait)]
                    ):
                        fmt = api_trait_fmt_args(arch, dtype, hdim, trait, max_bm0)
                        inners += FMHA_FWD_API_INNER_DISPATCH.format(
                            F_if=if_(i_trait),
                            F_trait_type=FMHA_FWD_TRAIT_TYPE.format(**fmt),
                            **fmt,
                        )
                    per_hdim_case += FMHA_FWD_API_PER_HDIM_CASE.format(
                        F_if=if_(i_hdim),
                        F_hdim=hdim,
                        F_hdim_v=hdim_v,
                        F_inner_dispatch=indent(inners),
                    )
                per_dtypes += FMHA_FWD_API_PER_DTYPE.format(
                    F_if=if_(i_dtype), F_dtype=dtype, F_hdim_case=indent(per_hdim_case)
                )
            per_arch += FMHA_FWD_API_PER_ARCH.format(
                F_if=if_(i_arch),
                F_arch=arch,
                F_dtype_case=indent(per_dtypes),
            )
        return FMHA_FWD_API_FUNC_TEMPLATE.format(
            F_func_name=func_name, F_dispatch=indent(per_arch)
        )

    def render_block_scale_size_kv(self) -> str:
        """Emit fmha_fwd_block_scale_size_kv(): a (arch, data type, head dims) ->
        kKVScaleAlign table over the instances that resolve finer than an N tile."""
        rows = str()
        for arch, pool_by_arch in self.pool.items():
            for dtype, pool_by_dtype in pool_by_arch.items():
                for (hdim, hdim_v), pool_by_hdim in pool_by_dtype.items():
                    traits = [
                        trait
                        for trait in pool_by_hdim
                        if emits_kvscale_align(trait.pipeline_tag, trait.qscale)
                    ]
                    if not traits:
                        continue
                    tiles = {
                        (t.bm0, t.bn0, t.bk0, t.bn1, t.bk1, t.bk0max) for t in traits
                    }
                    if len(tiles) != 1:
                        raise ValueError(
                            f"{arch.name}/{dtype}/d{hdim}x{hdim_v}: BLOCKSCALE instances of "
                            f"{KVSCALE_ALIGN_PIPELINE_TAGS} disagree about the tile ({tiles}), "
                            "so fmha_fwd_block_scale_size_kv() cannot tabulate them"
                        )
                    max_bm0 = max(t.bm0 for t in pool_by_hdim)
                    fmt = api_trait_fmt_args(arch, dtype, hdim, traits[0], max_bm0)
                    rows += FMHA_FWD_API_KVSCALE_ROW.format(
                        F_dtype_name=dtype,
                        F_hdim_v=hdim_v,
                        F_trait_type=FMHA_FWD_TRAIT_TYPE.format(**fmt),
                        **fmt,
                    )
        return FMHA_FWD_API_KVSCALE_TEMPLATE.format(
            F_lookup=FMHA_FWD_API_KVSCALE_LOOKUP.format(F_rows=rows) if rows else ""
        )


@dataclass
class FmhaFwdTileSize:
    F_bm0: int  # tile size along q seqlen (block size)
    F_bn0: int  # tile size along k seqlen
    F_bk0: int  # tile size along qk gemm unroll
    F_bn1: int  # tile size along v head_dim
    F_bk1: int  # tile size along kv gemm unroll
    F_bk0max: int  # total length of K0, used for pipeline that need load Q at once (or repeately load Q as a whole tile)
    F_rm0: int  # number of warps for gemm0 along q seqlen
    F_rn0: int  # number of warps for gemm0 along k seqlen
    F_rk0: int  # number of warps for gemm0 along head dim q (not used)
    F_rm1: int  # number of warps for gemm1 along q seqlen
    F_rn1: int  # number of warps for gemm1 along head dim v
    F_rk1: int  # number of warps for gemm1 along k seqlen (not used)
    F_wm0: int  # gemm0 warp size along m
    F_wn0: int  # gemm0 warp size along n
    F_wk0: int  # gemm0 warp size along k
    F_wm1: int  # gemm1 warp size along m
    F_wn1: int  # gemm1 warp size along n
    F_wk1: int  # gemm1 warp size along k
    F_occupancy: int  # occupancy, -1 will let pipeline decide the occupancy, other value will overwrite occupancy
    F_constraint: CppConstraint = field(default_factory=lambda: CppConstraint())

    @property
    def name(self) -> str:
        return (
            f"b{self.F_bm0}x{self.F_bn0}x{self.F_bk0}x{self.F_bn1}x{self.F_bk1}x{self.F_bk0max}"
            + f"_r{self.F_rm0}x{self.F_rn0}x{self.F_rk0}_r{self.F_rm1}x{self.F_rn1}x{self.F_rk1}"
            + f"_w{self.F_wm0}x{self.F_wn0}x{self.F_wk0}_w{self.F_wm1}x{self.F_wn1}x{self.F_wk1}"
            + ("" if self.F_occupancy == -1 else f"_o{self.F_occupancy}")
        )


@dataclass
class FmhaFwdKernel:
    F_arch: ArchTrait
    F_hdim: int  # hdim
    F_dtype: str  # data type
    F_mode: str  # value from MODE_MAP
    F_tile: FmhaFwdTileSize
    F_pipeline: FmhaFwdPipeline

    _KERNEL_HEADER: ClassVar[str] = FMHA_FWD_KERNEL_HEADER
    _KERNEL_HEADER_QR_HPAD: ClassVar[str] = FMHA_FWD_KERNEL_HEADER_QR_HPAD
    _KERNEL_BODY_TEMPLATE: ClassVar[str] = FMHA_FWD_KERNEL_BODY_TEMPLATE

    @classmethod
    def _get_cpp_kernel_class_name(cls, pipeline_tag):
        if pipeline_tag == "qr_async_trload_v3":
            return "ck_tile::FmhaFwdV3Kernel"
        else:
            return "ck_tile::FmhaFwdKernel"

    @classmethod
    def _get_kernel_header(cls, pipeline_tag):
        if pipeline_tag == "qr_hpad":
            return cls._KERNEL_HEADER_QR_HPAD
        return cls._KERNEL_HEADER

    @classmethod
    def _get_cpp_kargs_creator_func_name(cls, pipeline_tag):
        if pipeline_tag == "qr_async_trload_v3":
            return "fmha_fwd_v3_create_kargs_and_grids"
        else:
            return "fmha_fwd_create_kargs_and_grids"

    def render(self) -> str:
        body = type(self)._get_kernel_header(self.F_pipeline.tag) + type(
            self
        )._KERNEL_BODY_TEMPLATE.format(
            F_kname=self.name,
            F_arch=self.F_arch,
            F_hdim=self.F_hdim,
            F_dtype=FWD_DTYPE_MAP[self.F_dtype],
            F_bm0=self.F_tile.F_bm0,
            F_bn0=self.F_tile.F_bn0,
            F_bk0=self.F_tile.F_bk0,
            F_bn1=self.F_tile.F_bn1,
            F_bk1=self.F_tile.F_bk1,
            F_bk0max=self.F_tile.F_bk0max,
            F_rm0=self.F_tile.F_rm0,
            F_rn0=self.F_tile.F_rn0,
            F_rk0=self.F_tile.F_rk0,
            F_rm1=self.F_tile.F_rm1,
            F_rn1=self.F_tile.F_rn1,
            F_rk1=self.F_tile.F_rk1,
            F_wm0=self.F_tile.F_wm0,
            F_wn0=self.F_tile.F_wn0,
            F_wk0=self.F_tile.F_wk0,
            F_wm1=self.F_tile.F_wm1,
            F_wn1=self.F_tile.F_wn1,
            F_wk1=self.F_tile.F_wk1,
            F_vlayout=LAYOUT_MAP[self.F_pipeline.F_vlayout],
            F_spad=BOOL_MAP[self.F_pipeline.F_spad],
            F_skpad=BOOL_MAP[self.F_pipeline.F_skpad],
            F_dpad=BOOL_MAP[self.F_pipeline.F_dpad],
            F_dvpad=BOOL_MAP[self.F_pipeline.F_dvpad],
            F_logits=BOOL_MAP[self.F_pipeline.F_logits],
            F_bias=BIAS_MAP[self.F_pipeline.F_bias],
            F_lse=BOOL_MAP[self.F_pipeline.F_lse],
            F_dropout=BOOL_MAP[self.F_pipeline.F_dropout],
            F_qscale=QSCALE_MAP[self.F_pipeline.F_qscale],
            F_skip=BOOL_MAP[self.F_pipeline.F_skip],
            F_occupancy=self.F_tile.F_occupancy,
            F_pipeline_enum=PIPELINE_ENUM_MAP[self.F_pipeline.tag],
            F_mask=get_mask_cpp_type(self.F_pipeline.F_mask),
            F_mode=MODE_MAP[self.F_mode],
            F_trload=BOOL_MAP[self.F_pipeline.F_trload],
            F_pipeline=PIPELINE_MAP[self.F_pipeline.tag],
            F_kernel=self._get_cpp_kernel_class_name(self.F_pipeline.tag),
            F_kargs_creator=self._get_cpp_kargs_creator_func_name(self.F_pipeline.tag),
            F_sink=BOOL_MAP[self.F_pipeline.F_sink],
        )
        if emits_kvscale_align(self.F_pipeline.tag, self.F_pipeline.F_qscale):
            body += FMHA_FWD_KVSCALE_ALIGN_TEMPLATE.format(F_arch=self.F_arch)
        return body

    @property
    def name(self) -> str:
        # TODO: we don't encode idx here
        return (
            f"fmha_fwd_d{self.F_hdim}_{self.F_dtype}_{self.F_mode}_"
            + self.F_tile.name
            + "_"
            + self.F_pipeline.name
        )

    @property
    def filename(self) -> str:
        return f"{self.name}{self.F_arch.filename_suffix}.cpp"

    def api_trait(self) -> FmhaFwdApiTrait:
        return FmhaFwdApiTrait(
            arch=self.F_arch,
            pipeline_tag=self.F_pipeline.tag,
            hdim=str(self.F_hdim),
            dtype=self.F_dtype,
            mode=self.F_mode,
            bm0=self.F_tile.F_bm0,
            bn0=self.F_tile.F_bn0,
            bk0=self.F_tile.F_bk0,
            bn1=self.F_tile.F_bn1,
            bk1=self.F_tile.F_bk1,
            bk0max=self.F_tile.F_bk0max,
            vlayout=self.F_pipeline.F_vlayout,
            mask=self.F_pipeline.F_mask,
            logits=self.F_pipeline.F_logits,
            bias=self.F_pipeline.F_bias,
            lse=self.F_pipeline.F_lse,
            dropout=self.F_pipeline.F_dropout,
            qscale=self.F_pipeline.F_qscale,
            spad=self.F_pipeline.F_spad,
            skpad=self.F_pipeline.F_skpad,
            dpad=self.F_pipeline.F_dpad,
            dvpad=self.F_pipeline.F_dvpad,
            skip=self.F_pipeline.F_skip,
            tr_load=self.F_pipeline.F_trload,
            sink=self.F_pipeline.F_sink,
            occupancy=int(self.F_tile.F_occupancy),
            constraint=self.F_tile.F_constraint & self.F_pipeline.F_constraint,
        )


@dataclass
class ProblemContext:
    dtype: str
    mode: str
    hdim: int
    hdim_v: int


@dataclass
class KernelContext:
    tile: FmhaFwdTileSize
    pipeline: FmhaFwdPipeline
    mask_impl: str


CompatibilityRule = Callable[[ProblemContext, KernelContext], bool]


def is_compatible(
    problem_ctx: ProblemContext,
    kernel_ctx: KernelContext,
    rules: Iterable[CompatibilityRule],
) -> bool:
    return all(rule(problem_ctx, kernel_ctx) for rule in rules)


def create_kernel(
    arch: ArchTrait, problem_ctx: ProblemContext, kernel_ctx: KernelContext
) -> FmhaFwdKernel:
    return FmhaFwdKernel(
        F_arch=arch,
        F_dtype=problem_ctx.dtype,
        F_mode=problem_ctx.mode,
        F_hdim=problem_ctx.hdim,
        F_tile=kernel_ctx.tile,
        F_pipeline=kernel_ctx.pipeline,
    )


class CompatibilityRuleFactory:
    @staticmethod
    def get_rules() -> List[CompatibilityRule]:
        # in group mode, spad/skpad must be true, since we can't predict if seqlen of current batch need pad or not
        def check_mode(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            if problem_ctx.mode == "group":
                if (
                    kernel_ctx.pipeline.F_spad != "t"
                    or kernel_ctx.pipeline.F_skpad != "t"
                ):
                    return False
            return True

        def check_hdim(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            # NOTE: this is used to speedup deepseek prefill case, we don't gen training
            if (problem_ctx.hdim, problem_ctx.hdim_v) == (192, 128):
                if (
                    kernel_ctx.pipeline.F_bias != "no"
                    or kernel_ctx.pipeline.F_dropout == "t"
                ):
                    return False
            return True

        def check_feature(
            problem_ctx: ProblemContext, kernel_ctx: KernelContext
        ) -> bool:
            # logits_soft_cap is only allowed if no bias
            if not (
                (
                    kernel_ctx.pipeline.F_logits == "t"
                    and kernel_ctx.pipeline.F_bias == "no"
                )
                or kernel_ctx.pipeline.F_logits == "f"
            ):
                return False
            return True

        return [check_mode, check_hdim, check_feature]


class CompatibilityRuleFactoryGfx9(CompatibilityRuleFactory):
    _AVAILABLE_PIPELINES = frozenset({"qr", "qr_async", "qs"})

    @classmethod
    def get_rules(cls) -> List[CompatibilityRule]:
        rules = CompatibilityRuleFactory.get_rules()

        def check_hdim_tile(
            problem_ctx: ProblemContext, kernel_ctx: KernelContext
        ) -> bool:
            # FIX: too confusing that it has to know about mx types
            if problem_ctx.dtype not in ("fp32", "mxfp8", "mxfp4"):
                # TODO: update if >=gfx11 archs get qr_async and qr_async_trload support
                if kernel_ctx.pipeline.tag in cls._AVAILABLE_PIPELINES and (
                    (
                        (problem_ctx.hdim, problem_ctx.hdim_v) == (128, 128)
                        and kernel_ctx.tile.F_bn0 != 128
                    )
                    or (
                        (problem_ctx.hdim, problem_ctx.hdim_v) != (128, 128)
                        and kernel_ctx.tile.F_bm0 != 128
                    )
                    or (
                        (problem_ctx.hdim, problem_ctx.hdim_v) == (128, 128)
                        and kernel_ctx.pipeline.tag != "qr_async"
                        and kernel_ctx.tile.F_bk0 == 64
                    )
                ):
                    # non qr_async_trload only support km0=128 tile size when hdim is not 128
                    # non qr_async only support kn0=128 tile size when hdim is 128
                    return False
            return True

        rules.append(check_hdim_tile)
        return rules


class CompatibilityRuleFactoryGfx950(CompatibilityRuleFactoryGfx9):
    _AVAILABLE_PIPELINES = (
        CompatibilityRuleFactoryGfx9._AVAILABLE_PIPELINES
        | frozenset({"qr_async_trload", "qr_async_trload_v3"})
    )

    @classmethod
    def get_rules(cls) -> List[CompatibilityRule]:
        rules = CompatibilityRuleFactoryGfx9.get_rules()

        def check_tile_pipeline(
            problem_ctx: ProblemContext, kernel_ctx: KernelContext
        ) -> bool:
            if kernel_ctx.pipeline.tag == "qr_async_trload" and (
                (
                    (problem_ctx.hdim, problem_ctx.hdim_v) == (128, 128)
                    and kernel_ctx.tile.F_bn0 == 128
                )
                or (
                    (problem_ctx.hdim, problem_ctx.hdim_v)
                    not in [(64, 64), (128, 128), (256, 256)]
                )
            ):
                return False

            # only qr_async_trload_v3 use km0=256 & 8-warps
            is_v3_dedicated_tile = (
                kernel_ctx.tile.F_bm0 == 256
                and (kernel_ctx.tile.F_rm0 * kernel_ctx.tile.F_rn0 * kernel_ctx.tile.F_rk0) == 8
                and (kernel_ctx.tile.F_rm1 * kernel_ctx.tile.F_rn1 * kernel_ctx.tile.F_rk1) == 8
            )  # fmt: skip
            is_v3_pipeline = kernel_ctx.pipeline.tag == "qr_async_trload_v3"
            return is_v3_dedicated_tile == is_v3_pipeline

        rules.extend([check_tile_pipeline])
        return rules


class KernelComponentFactoryGfx9(CompatibilityRuleFactoryGfx9):
    arch = ArchTrait(
        "gfx9", preprocessor_check="defined(__gfx9__) && !defined(__gfx950__)"
    )

    _DT_FP32 = ("fp32",)
    _DT_FP16_BF16 = ("fp16", "bf16")
    _DT_FP8 = ("fp8",)
    _DT_FP8BF16 = ("fp8bf16",)
    _DT_FP8FP32 = ("fp8fp32",)

    @classmethod
    def supported_dtypes(cls) -> Tuple[str]:
        return (
            cls._DT_FP32
            + cls._DT_FP16_BF16
            + cls._DT_FP8
            + cls._DT_FP8BF16
            + cls._DT_FP8FP32
        )

    # TODO: design a more practical way to do it
    # this is current supported tile size per hdim
    @classmethod
    def get_hdim_tile_size_dict(cls, dtype: str) -> Optional[dict]:
        if dtype in cls._DT_FP32:
            return {
                #                             bm0, bn0, bk0, bn1, bk1,
                ( 32,  32) : [FmhaFwdTileSize( 64,  64,  16,  32,  32,  32,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                ( 48,  48) : [FmhaFwdTileSize( 32, 128,  16,  48,  16,  48,  2, 1, 1,  2, 1, 1,  16, 16, 16,  16, 16, 16,  -1),
                              FmhaFwdTileSize(128,  64,  16,  48,  32,  48,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                ( 64,  64) : [FmhaFwdTileSize( 64,  64,  32,  64,  32,  64,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                ( 96, 128) : [FmhaFwdTileSize(128,  64,  32, 128,  32,  96,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                (128, 128) : [FmhaFwdTileSize( 32, 128,  32, 128,  16, 128,  2, 1, 1,  2, 1, 1,  16, 16, 16,  16, 16, 16,  -1),
                              FmhaFwdTileSize(128,  64,  32, 128,  32, 128,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                (192, 192) : [FmhaFwdTileSize( 64,  64,  32, 192,  32, 192,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                (256, 256) : [FmhaFwdTileSize( 64,  64,  32, 256,  32, 256,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
            }  # fmt: skip
        elif dtype in cls._DT_FP16_BF16:
            return {
                ( 32,  32) : [FmhaFwdTileSize(128,  64,  16,  32,  32,  32,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,  -1)],
                ( 64,  64) : [FmhaFwdTileSize( 16,  32,  64,  64,  32,  64,  1, 1, 1,  1, 1, 1,  16, 16, 32,  16, 16, 32,  -1),
                              FmhaFwdTileSize( 32,  32,  64,  64,  32,  64,  1, 1, 1,  1, 1, 1,  32, 32, 16,  32, 32, 16,  -1),
                              FmhaFwdTileSize(128,  64,  32,  64,  32,  64,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,  -1)],
                ( 80, 96)  : [FmhaFwdTileSize(128, 128,  16,  96,  32,  80,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,  -1)],
                ( 96, 128) : [FmhaFwdTileSize(128, 128,  32, 128,  32,  96,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,  -1)],
                (128, 128) : [FmhaFwdTileSize( 16,  32,  64, 128,  32, 128,  1, 1, 1,  1, 1, 1,  16, 16, 32,  16, 16, 32,  -1),
                              FmhaFwdTileSize( 32,  32, 128, 128,  32, 128,  1, 1, 1,  1, 1, 1,  32, 32, 16,  32, 32, 16,  -1),
                              FmhaFwdTileSize( 64, 128,  32, 128,  32, 128,  4, 1, 1,  4, 1, 1,  16, 16, 32,  16, 16, 16,  -1, CppConstraint('get_num_blocks(64) <= num_cus')),
                              FmhaFwdTileSize(128,  64,  32, 128,  16, 128,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,  -1),
                              FmhaFwdTileSize(128, 128,  32, 128,  32, 128,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,  -1)],
              # (160, 160) : [FmhaFwdTileSize(128, 128 , 32, 160,  32, 160,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,   1)],
                (192, 128) : [FmhaFwdTileSize(128, 128,  32, 128,  32, 192,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,  -1)],
                (192, 192) : [FmhaFwdTileSize(128, 128,  32, 192,  32, 192,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,   1)],
                (256, 256) : [FmhaFwdTileSize(128, 128,  32, 256,  32, 256,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,  -1)],
            }  # fmt: skip
        elif dtype in cls._DT_FP8 or dtype in cls._DT_FP8BF16:
            return {
                ( 64,  64) : [FmhaFwdTileSize(128,  64,  32,  64,  32,  64,  2, 1, 1,  2, 1, 1,  32, 32, 32,  32, 32, 32,  -1)],
                (128, 128) : [FmhaFwdTileSize(128, 128,  32, 128,  32, 128,  4, 1, 1,  4, 1, 1,  32, 32, 32,  32, 32, 32,  -1)],
                (192, 128) : [FmhaFwdTileSize(128, 128,  32, 128,  32, 192,  4, 1, 1,  4, 1, 1,  32, 32, 32,  32, 32, 32,  -1)],
                (256, 256) : [FmhaFwdTileSize(128, 128,  32, 256,  32, 256,  4, 1, 1,  4, 1, 1,  32, 32, 32,  32, 32, 32,  -1)],
            }  # fmt: skip
        elif dtype in cls._DT_FP8FP32:
            return {
                (128, 128) : [FmhaFwdTileSize(128, 128,  32, 128,  32, 128,  4, 1, 1,  4, 1, 1,  32, 32, 32,  32, 32, 32,  -1)],
            }  # fmt: skip

    # TODO: we don't support tuning yet, so pick up one value for vlayout/pipeline/pad
    #       support this in future
    @classmethod
    def get_pipelines(
        cls, dtype, hdim, hdim_v, receipt, mask_impl
    ) -> List[FmhaFwdPipeline]:
        # this function will populate a list possible pipelines
        # TODO: the order of List matters! the later in this list will be also be checked later
        # TODO: currently for qr pipeline, let "t" padding to appear later!!
        # TODO: how to design this more generic?
        pipelines = []
        if dtype in cls._DT_FP32:
            qscale = "no"
            for logits, mask, bias, lse, dropout, skip, sink in itertools.product(
                ["t", "f"],
                get_mask_map(mask_impl).keys(),
                BIAS_MAP.keys(),
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
            ):
                pipelines.append(FmhaFwdPipeline("qr", "row", "f", "f", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr", "row", "f", "t", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
        elif dtype in cls._DT_FP16_BF16:
            qscale = "no"
            for logits, mask, bias, lse, dropout, skip, sink in itertools.product(
                ["t", "f"],
                get_mask_map(mask_impl).keys(),
                BIAS_MAP.keys(),
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
            ):
                if hdim == 256 and hdim_v == 256:
                    pipelines.append(FmhaFwdPipeline("qr", "row", "f", "f", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                    # the below two is used for hdim vectorize load
                    pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                else:
                    if bias == "bias":
                        # TODO: rocm 6.2 compiler problem if using qr_async for bias case
                        pipelines.append(FmhaFwdPipeline("qr", "row", "f", "f", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                        pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                    else:
                        # skpad=f + dpad=t/dvpad=t variant covers padded head dims (e.g. d=16, d=160)
                        # when seqlen_k is divisible by bn0. Restored after #6526 changed it to
                        # "f","f","f","f", which left those cases with no dispatchable qr_async kernel.
                        pipelines.append(FmhaFwdPipeline("qr_async", "row", "t", "f", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                        pipelines.append(FmhaFwdPipeline("qr_async", "row", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                    if receipt == 1 and bias != "bias":
                        pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip # TODO: cover arbitraty hdim# fmt: skip
        elif dtype in cls._DT_FP8BF16 or dtype in cls._DT_FP8FP32:
            # no need lse/dropout kernels
            for logits, qscale, mask, bias, sink in itertools.product(
                ["t", "f"],
                ["no", "pertensor", "blockscale"],
                get_mask_map(mask_impl).keys(),
                ["no"],
                ["f", "t"],
            ):
                if hdim == 64:
                    pipelines.append(FmhaFwdPipeline("qr", "row", "f", "f", "f", "f", logits, bias, "f", "f", qscale, mask, "f", "f", sink))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "t", "t", logits, bias, "f", "f", qscale, mask, "f", "f", sink))  # fmt: skip
                else:
                    # skpad=f + dpad=t/dvpad=t variant covers padded head dims when seqlen_k is
                    # divisible by bn0. Restored after #6526 changed it to "f","f","f","f".
                    pipelines.append(FmhaFwdPipeline("qr_async", "row", "t", "f", "t", "t", logits, bias, "f", "f", qscale, mask, "f", "f", sink))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr_async", "row", "t", "t", "t", "t", logits, bias, "f", "f", qscale, mask, "f", "f", sink))  # fmt: skip
        return pipelines


class KernelComponentFactoryGfx950(
    KernelComponentFactoryGfx9, CompatibilityRuleFactoryGfx950
):
    arch = ArchTrait("gfx950")

    _DT_MXFP8 = ("mxfp8",)
    _DT_MXFP4 = ("mxfp4",)

    @classmethod
    def supported_dtypes(cls) -> Tuple[str]:
        return (
            KernelComponentFactoryGfx9.supported_dtypes()
            + cls._DT_MXFP8
            + cls._DT_MXFP4
        )

    @classmethod
    def get_hdim_tile_size_dict(cls, dtype: str) -> Optional[dict]:
        result = KernelComponentFactoryGfx9.get_hdim_tile_size_dict(dtype)
        if dtype in cls._DT_FP16_BF16:
            # # add tile for qr_async_trload_v3 (bf16/fp16 V3 not ready)
            # if (128, 128) in result.keys():
            #     result[(128, 128)].append(
            #         FmhaFwdTileSize(256, 32, 128, 128, 32, 128,  8, 1, 1,  8, 1, 1,  32, 32, 16,  32, 32, 16,  -1))  # fmt: skip
            if (256, 256) in result.keys():
                result[(256, 256)] = [FmhaFwdTileSize(128,  64,  32, 256,  32, 256,  4, 1, 1,  4, 1, 1,  32, 32, 16,  32, 32, 16,  -1)]  # fmt: skip
        elif dtype in cls._DT_MXFP8:
            return {
                #                             bm0, bn0, bk0, bn1, bk1,
                (128, 128) : [FmhaFwdTileSize(128, 128,  64, 128,  64, 128,  4, 1, 1,  4, 1, 1,  32, 32,  64,  32, 32,  64,  -1)],
                (256, 256) : [FmhaFwdTileSize(128, 128, 128, 256, 128, 256,  4, 1, 1,  4, 1, 1,  16, 16, 128,  16, 16, 128,  -1)],
            }  # fmt: skip
        elif dtype in cls._DT_MXFP4:
            return {
                #                             bm0, bn0, bk0, bn1, bk1,
                (128, 128) : [FmhaFwdTileSize(128, 128,  64, 128,  64, 128,  4, 1, 1,  4, 1, 1,  32, 32,  64,  32, 32,  64,  -1)],
                (256, 256) : [FmhaFwdTileSize(128, 128, 128, 256, 128, 256,  4, 1, 1,  4, 1, 1,  16, 16, 128,  16, 16, 128,  -1)],
            }  # fmt: skip
        elif dtype in cls._DT_FP8BF16:
            if (128, 128) in result.keys():
                result[(128, 128)].append(
                    FmhaFwdTileSize(256, 64, 128, 128, 64, 128,  8, 1, 1,  8, 1, 1,  32, 32, 32,  32, 32, 32,  -1))  # fmt: skip
        return result

    @classmethod
    def get_pipelines(
        cls, dtype, hdim, hdim_v, receipt, mask_impl
    ) -> List[FmhaFwdPipeline]:
        pipelines = KernelComponentFactoryGfx9.get_pipelines(
            dtype, hdim, hdim_v, receipt, mask_impl
        )
        if dtype in cls._DT_FP16_BF16:
            qscale = "no"
            for logits, mask, bias, lse, dropout, skip, sink in itertools.product(
                ["t", "f"],
                get_mask_map(mask_impl).keys(),
                BIAS_MAP.keys(),
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
            ):
                if (
                    (hdim, hdim_v) in [(64, 64), (128, 128), (256, 256)]
                    and logits == "f"
                    and bias == "no"
                    and dropout == "f"
                    and skip == "f"
                ):
                    pipelines.append(FmhaFwdPipeline("qr_async_trload", "row", "f", "f", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "t", sink))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr_async_trload", "row", "f", "f", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "t", sink))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr_async_trload", "row", "t", "t", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "t", sink))  # fmt: skip  # group mode spad

            # # qr_async_trload_v3 bf16/fp16 not ready
            # if (hdim, hdim_v) == (128, 128):
            #     for logits, mask in itertools.product(["t", "f"], ["no", "causal"]):
            #         pipelines.append(FmhaFwdPipeline("qr_async_trload_v3", "row", "t", "t", "f", "f",
            #             F_logits=logits, F_bias="no", F_lse="f", F_dropout="f", F_qscale=qscale, F_mask=mask, F_skip="f", F_trload="t", F_sink="f"))  # fmt: skip
        elif dtype in cls._DT_FP8BF16:
            # qr_async_trload_v3 only supports (generic) causal mask
            for logits, qscale, mask, lse in itertools.product(
                ["t", "f"],
                ["no", "pertensor"],
                ["no", "causal"],
                ["t", "f"],
            ):
                pipelines.append(FmhaFwdPipeline("qr_async_trload_v3", "row", "t", "t", "f", "f", F_logits=logits, F_bias="no", F_lse=lse, F_dropout="f", F_qscale=qscale, F_mask=mask, F_skip="f", F_trload="t", F_sink="f"))  # fmt: skip

        elif dtype in cls._DT_MXFP8 or dtype in cls._DT_MXFP4:
            # no need dropout kernels
            lse = "t"
            dropout = "f"
            for logits, qscale, mask, bias, sink in itertools.product(
                ["f"],
                ["mx"],
                get_mask_map(mask_impl).keys(),
                ["no"],
                ["f", "t"],
            ):
                pipelines.append(FmhaFwdPipeline("qr", "col", "f", "f", "f", "f", logits, bias, lse, dropout, qscale, mask, "f", "f", sink))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr", "col", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, "f", "f", sink))  # fmt: skip
                if hdim > 64 and dtype in cls._DT_MXFP8:
                    pipelines.append(FmhaFwdPipeline("qr_async", "col", "f", "f", "f", "f", logits, bias, lse, dropout, qscale, mask, "f", "f", sink))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr_async", "col", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, "f", "f", sink))  # fmt: skip
        return pipelines


class KernelComponentFactoryGfx11(CompatibilityRuleFactory):
    arch = ArchTrait(
        "gfx11",
        preprocessor_check="defined(__gfx11__) && !defined(__gfx115__)",
    )

    _DT_FP16_BF16 = ("fp16", "bf16")

    @classmethod
    def supported_dtypes(cls) -> Tuple[str]:
        return cls._DT_FP16_BF16

    @classmethod
    def get_rules(cls) -> List[CompatibilityRule]:
        rules = super().get_rules()

        def check_d128_tile_pipeline(
            problem_ctx: ProblemContext, kernel_ctx: KernelContext
        ) -> bool:
            if problem_ctx.dtype not in cls._DT_FP16_BF16:
                return True

            if (problem_ctx.hdim, problem_ctx.hdim_v) != (128, 128):
                return True

            # For (128, 128) head dims, partial-fragment support in qr_hpad removes the need
            # for the previous qr_hpad-specific handling that was added to avoid register spill.
            # qr_hpad now reuses the regular 128x64 tile choice.
            # The 64x64 tile remains disabled for qr_hpad because it is consistently slower
            # in our measurements.
            if kernel_ctx.tile.F_bm0 == 64 and kernel_ctx.tile.F_bn0 == 64:
                return kernel_ctx.pipeline.tag != "qr_hpad"

            return True

        rules.append(check_d128_tile_pipeline)
        return rules

    @classmethod
    def get_hdim_tile_size_dict(cls, dtype: str) -> Optional[dict]:
        if dtype in cls._DT_FP16_BF16:
            return {
                #                             bm0, bn0, bk0, bn1, bk1,
                ( 32,  32) : [FmhaFwdTileSize( 64,  64,  16,  32,  32,   32,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                ( 64,  64) : [FmhaFwdTileSize( 64,  64,  32,  64,  32,   64,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1, CppConstraint("a.max_seqlen_q < 4096")),
                              FmhaFwdTileSize(128,  64,  32,  64,  32,   64,  8, 1, 1,  8, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                (128, 128) : [FmhaFwdTileSize(128,  64,  32, 128,  32,  128,  8, 1, 1,  8, 1, 1,  16, 16, 16,  16, 16, 16,   6)],
                (192, 128) : [FmhaFwdTileSize( 64,  64,  32, 128,  32,  256,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                (256, 256) : [FmhaFwdTileSize(128,  64,  32, 256,  32,  256,  8, 1, 1,  8, 1, 1,  16, 16, 16,  16, 16, 16,   6)]
            }  # fmt: skip
        else:
            raise ValueError(f"unsupported dtype={dtype}")

    @classmethod
    def get_pipelines(
        cls, dtype, hdim, hdim_v, receipt, mask_impl
    ) -> List[FmhaFwdPipeline]:
        pipelines = []
        if dtype in cls._DT_FP16_BF16:
            qscale = "no"
            for logits, mask, bias, lse, dropout, skip, sink in itertools.product(
                ["t", "f"],
                get_mask_map(mask_impl).keys(),
                BIAS_MAP.keys(),
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
            ):
                # Keep only ttff/tttt for gfx11: ffff path is often similar or worse
                # pipelines.append(FmhaFwdPipeline("qr", "row", "f", "f", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr_hpad", "row", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                if receipt == 1:
                    pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
        return pipelines


class KernelComponentFactoryGfx115(KernelComponentFactoryGfx11):
    arch = ArchTrait("gfx115")

    @classmethod
    def get_hdim_tile_size_dict(cls, dtype: str) -> Optional[dict]:
        result = super().get_hdim_tile_size_dict(dtype)
        if dtype in cls._DT_FP16_BF16:
            result[(64, 64)] = [FmhaFwdTileSize( 64,  64,  32,  64,  32,   64,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)]  # fmt: skip
            result[(256, 256)] = [FmhaFwdTileSize(128,  64,  32, 256,  32,  256,  8, 1, 1,  8, 1, 1,  16, 16, 16,  16, 16, 16,  -1)]  # fmt: skip
        return result


class KernelComponentFactoryGfx12(CompatibilityRuleFactory):
    arch = ArchTrait("gfx12")

    _DT_FP16_BF16 = ("fp16", "bf16")
    _DT_FP8_FP8BF16 = ("fp8", "fp8bf16")
    _DT_FP8FP32 = ("fp8fp32",)

    @classmethod
    def supported_dtypes(cls) -> Tuple[str]:
        return cls._DT_FP16_BF16 + cls._DT_FP8_FP8BF16 + cls._DT_FP8FP32

    @classmethod
    def get_hdim_tile_size_dict(cls, dtype: str) -> Optional[dict]:
        if dtype in cls._DT_FP16_BF16:
            return {
                #                             bm0, bn0, bk0, bn1, bk1,
                ( 32,  32) : [FmhaFwdTileSize( 64,  64,  16,  32,  32,   32,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                ( 64,  64) : [FmhaFwdTileSize( 64,  64,  32,  64,  32,   64,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                (128, 128) : [FmhaFwdTileSize(128,  64,  32, 128,  32,  128,  8, 1, 1,  8, 1, 1,  16, 16, 16,  16, 16, 16,   6)],
                (192, 128) : [FmhaFwdTileSize( 64,  64,  32, 128,  32,  256,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                (256, 256) : [FmhaFwdTileSize( 64,  64,  32, 256,  32,  256,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
            }  # fmt: skip
        elif dtype in cls._DT_FP8_FP8BF16:
            return {
                #                             bm0, bn0, bk0, bn1, bk1,
                ( 64,  64) : [FmhaFwdTileSize(128,  64,  32,  64,  32,   64,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                (128, 128) : [FmhaFwdTileSize( 64,  64,  32, 128,  32,  128,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
                (256, 256) : [FmhaFwdTileSize( 64,  32,  32, 256,  32,  256,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
            }  # fmt: skip
        elif dtype in cls._DT_FP8FP32:
            return {
                #                             bm0, bn0, bk0, bn1, bk1,
                (128, 128) : [FmhaFwdTileSize( 64,  64,  32, 128,  32,  128,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1)],
            }  # fmt: skip
        else:
            raise ValueError(f"unsupported dtype={dtype}")

    @classmethod
    def get_pipelines(
        cls, dtype, hdim, hdim_v, receipt, mask_impl
    ) -> List[FmhaFwdPipeline]:
        pipelines = []
        if dtype in cls._DT_FP16_BF16:
            qscale = "no"
            for logits, mask, bias, lse, dropout, skip, sink in itertools.product(
                ["t", "f"],
                get_mask_map(mask_impl).keys(),
                BIAS_MAP.keys(),
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
            ):
                # pipelines.append(FmhaFwdPipeline("qr", "row", "f", "f", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr_hpad", "row", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                if receipt == 1:
                    pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
        elif dtype in cls._DT_FP8_FP8BF16 or dtype in cls._DT_FP8FP32:
            # no need lse/dropout kernels
            for logits, qscale, mask, bias in itertools.product(
                ["f"],
                ["no", "pertensor", "blockscale"],
                get_mask_map(mask_impl).keys(),
                ["no"],
            ):
                pipelines.append(FmhaFwdPipeline("qr", "row", "f", "f", "f", "f", logits, bias, "f", "f", qscale, mask, "f", "f", "f"))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "f", "f", logits, bias, "f", "f", qscale, mask, "f", "f", "f"))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "t", "t", logits, bias, "f", "f", qscale, mask, "f", "f", "f"))  # fmt: skip
        return pipelines

class KernelComponentFactoryGfx125(CompatibilityRuleFactory):
    arch = ArchTrait("gfx125")

    _DT_FP16_BF16 = ("fp16", "bf16")
    _DT_FP8_FP8BF16 = ("fp8", "fp8bf16")
    _DT_FP8FP32 = ("fp8fp32",)

    @classmethod
    def supported_dtypes(cls) -> Tuple[str]:
        return cls._DT_FP16_BF16 + cls._DT_FP8_FP8BF16 + cls._DT_FP8FP32

    @classmethod
    def get_hdim_tile_size_dict(cls, dtype: str) -> Optional[dict]:
        if dtype in cls._DT_FP16_BF16:
            return {
                #                             bm0, bn0, bk0, bn1, bk1,
                ( 32,  32) : [FmhaFwdTileSize( 64,  64,  32,  32,  32,   64,  4, 1, 1,  4, 1, 1,  16, 16, 32,  16, 16, 32,  -1)],
                ( 64,  64) : [FmhaFwdTileSize( 64,  64,  32,  64,  32,   64,  4, 1, 1,  4, 1, 1,  16, 16, 32,  16, 16, 32,  -1)],
                (128, 128) : [FmhaFwdTileSize( 64,  64,  32, 128,  32,  128,  4, 1, 1,  4, 1, 1,  16, 16, 32,  16, 16, 32,  -1, CppConstraint("a.max_seqlen_q < 2048")),
                              FmhaFwdTileSize(128,  64,  32, 128,  32,  128,  4, 1, 1,  4, 1, 1,  16, 16, 32,  16, 16, 32,  -1)],
                (192, 128) : [FmhaFwdTileSize( 64,  64,  32, 128,  32,  256,  4, 1, 1,  4, 1, 1,  16, 16, 32,  16, 16, 32,  -1)],
                (256, 256) : [FmhaFwdTileSize( 64,  64,  32, 256,  32,  256,  4, 1, 1,  4, 1, 1,  16, 16, 32,  16, 16, 32,  -1)],
            }  # fmt: skip
        elif dtype in cls._DT_FP8_FP8BF16:
            return {
                #                             bm0, bn0, bk0, bn1, bk1,
                ( 64,  64) : [FmhaFwdTileSize( 64, 128,  64,  64, 128,   64,  4, 1, 1,  4, 1, 1,  16, 16, 64,  16, 16, 128,  -1),
                              FmhaFwdTileSize(128,  64,  64,  64,  64,  128,  4, 1, 1,  4, 1, 1,  16, 16, 64,  16, 16, 64,  -1)],
                (128, 128) : [FmhaFwdTileSize( 64, 128, 128, 128, 128,  128,  4, 1, 1,  4, 1, 1,  16, 16, 128,  16, 16, 128,  -1),
                              FmhaFwdTileSize( 64,  64,  64, 128,  64,  128,  4, 1, 1,  4, 1, 1,  16, 16, 64,  16, 16, 64,  -1)],
                #(256, 256) : [FmhaFwdTileSize( 64,  32,  64, 256,  64,  256,  4, 1, 1,  4, 1, 1,  16, 16, 64,  16, 16, 64,  -1)],
            }  # fmt: skip
        elif dtype in cls._DT_FP8FP32:
            return {
                #                             bm0, bn0, bk0, bn1, bk1,
                (128, 128) : [FmhaFwdTileSize( 64, 128, 128, 128, 128,  128,  4, 1, 1,  4, 1, 1,  16, 16, 128,  16, 16, 128,  -1),
                              FmhaFwdTileSize( 64,  64,  64, 128,  64,  128,  4, 1, 1,  4, 1, 1,  16, 16, 64,  16, 16, 64,  -1)],
            }  # fmt: skip
        else:
            raise ValueError(f"unsupported dtype={dtype}")

    @classmethod
    def get_rules(cls) -> List[CompatibilityRule]:
        def check_gemm0_k(
            problem_ctx: ProblemContext, kernel_ctx: KernelContext
        ) -> bool:
            # qr's k0 prefetch needs >= 2 loops; qr_tdm has none and takes the 1-loop tile.
            if problem_ctx.dtype not in cls._DT_FP8_FP8BF16 + cls._DT_FP8FP32:
                return True
            k0_loops = kernel_ctx.tile.F_bk0max // kernel_ctx.tile.F_bk0
            if kernel_ctx.pipeline.tag == "qr_tdm":
                return k0_loops == 1
            return k0_loops >= 2

        return [*super().get_rules(), check_gemm0_k]

    @classmethod
    def get_pipelines(
        cls, dtype, hdim, hdim_v, receipt, mask_impl
    ) -> List[FmhaFwdPipeline]:
        pipelines = []
        if dtype in cls._DT_FP16_BF16:
            qscale = "no"
            # qr_tdm: gfx1250 TDM pipeline, preferred for d=128.
            # Emitted first so runtime dispatcher selects qr_tdm over qr
            # when both match (dispatch order = list order in generated code).
            # NOTE: dropout is not yet implemented in qr_tdm — only emit
            # dropout="f" so dropout workloads fall through to qr.
            # Logits soft cap is not implemented either, so pin logits="f".
            if hdim == 128 and hdim_v == 128:
                for logits, mask, bias, lse, sink in itertools.product(
                    ["f"],
                    get_mask_map(mask_impl).keys(),
                    BIAS_MAP.keys(),
                    ["t", "f"],
                    ["t", "f"],
                ):
                    pipelines.append(FmhaFwdPipeline("qr_tdm", "row", "f", "f", "f", "f", logits, bias, lse, "f", qscale, mask, "f", "f", sink))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr_tdm", "row", "f", "f", "t", "t", logits, bias, lse, "f", qscale, mask, "f", "f", sink))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr_tdm", "row", "t", "t", "f", "f", logits, bias, lse, "f", qscale, mask, "f", "f", sink))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr_tdm", "row", "t", "t", "t", "t", logits, bias, lse, "f", qscale, mask, "f", "f", sink))  # fmt: skip

            # qr: generic pipeline fallback for trait combos not covered by
            # qr_tdm (e.g., bias, dropout, skip, d!=128).
            for logits, mask, bias, lse, dropout, skip, sink in itertools.product(
                ["t", "f"],
                get_mask_map(mask_impl).keys(),
                BIAS_MAP.keys(),
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
                ["t", "f"],
            ):
                pipelines.append(FmhaFwdPipeline("qr", "row", "f", "f", "f", "f", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "t", "t", logits, bias, lse, dropout, qscale, mask, skip, "f", sink))  # fmt: skip
        elif dtype in cls._DT_FP8_FP8BF16 or dtype in cls._DT_FP8FP32:
            # no need dropout kernels. Alibi is held back: its near-one-hot P leaves a
            # slope-dependent quantization bias the OUT gain check reads as a systematic error.
            if (hdim, hdim_v) in ((128, 128), (64, 64)):
                for logits, qscale, mask, bias, lse in itertools.product(
                    ["f"],
                    ["no", "pertensor", "perhead", "blockscale"],
                    get_mask_map(mask_impl).keys(),
                    ["no", "bias"],
                    ["f", "t"],
                ):
                    pipelines.append(FmhaFwdPipeline("qr_tdm", "row", "f", "f", "f", "f", logits, bias, lse, "f", qscale, mask, "f", "f", "f"))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr_tdm", "row", "f", "f", "t", "t", logits, bias, lse, "f", qscale, mask, "f", "f", "f"))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr_tdm", "row", "t", "t", "f", "f", logits, bias, lse, "f", qscale, mask, "f", "f", "f"))  # fmt: skip
                    pipelines.append(FmhaFwdPipeline("qr_tdm", "row", "t", "t", "t", "t", logits, bias, lse, "f", qscale, mask, "f", "f", "f"))  # fmt: skip

            for logits, qscale, mask, bias in itertools.product(
                ["f"], ["no", "pertensor"], get_mask_map(mask_impl).keys(), ["no"]
            ):
                pipelines.append(FmhaFwdPipeline("qr", "row", "f", "f", "f", "f", logits, bias, "f", "f", qscale, mask, "f", "f", "f"))  # fmt: skip
                pipelines.append(FmhaFwdPipeline("qr", "row", "t", "t", "t", "t", logits, bias, "f", "f", qscale, mask, "f", "f", "f"))  # fmt: skip
        return pipelines

class CustomFactory(KernelComponentFactoryGfx9, CompatibilityRuleFactoryGfx9):
    @classmethod
    def get_hdim_tile_size_dict(cls, dtype: str) -> Optional[dict]:
        result = KernelComponentFactoryGfx9.get_hdim_tile_size_dict(dtype)
        if dtype in cls._DT_FP16_BF16:
            if (128, 128) in result.keys():
                result[(128, 128)].insert(0, FmhaFwdTileSize( 64, 128, 64, 128, 64,  128,  4, 1, 1,  4, 1, 1,  16, 16, 16,  16, 16, 16,  -1, CppConstraint("get_num_blocks(128) < num_cus * min_cu_util_rate")))  # fmt: skip
        return result


# ---------------------------------------------------------------------------
# Custom tune-config driven factory
#
# When the env var CK_TILE_FMHA_FWD_CUSTOM_TUNE_CONFIG_FILE points to a JSON
# file, `get_factory` will build a dynamic factory that:
#   * inherits everything (arch, supported_dtypes, get_pipelines) from an
#     arch base factory (selected via the JSON "target" field);
#   * replaces `get_hdim_tile_size_dict` with the JSON-declared tile table,
#     so that codegen ONLY emits kernels for the (hdim, hdim_v) keys the
#     tuner asked for;
#   * optionally drops `check_hdim_tile` rule (needed for arbitrary padded
#     hdim combos such as (80, 96));
#   * appends a "filters" compatibility rule that narrows pipelines to a
#     concrete combo (mode / mask / bias / lse / dropout / logits / qscale /
#     vlayout / skip / sink / trload / spad / skpad / dpad / dvpad).
#
# JSON schema (v1):
# {
#   "schema_version": 1,
#   "target": "gfx942",
#   "dtypes": ["bf16"],
#   "tiles": {
#     "bf16": {
#       "80,96": [
#         {"F_bm0":64,"F_bn0":64,"F_bk0":32,"F_bn1":96,"F_bk1":32,
#          "F_bk0max":128,"F_rm0":4,"F_rn0":1,"F_rk0":1,
#          "F_rm1":4,"F_rn1":1,"F_rk1":1,
#          "F_wm0":16,"F_wn0":16,"F_wk0":32,
#          "F_wm1":16,"F_wn1":16,"F_wk1":32,"F_occupancy":-1}
#       ]
#     }
#   },
#   "filters": {
#     "mode": ["group"], "mask": ["mask_bottom_right"],
#     "bias": ["no"], "lse": ["f"], "dropout": ["f"],
#     "logits": ["f"], "qscale": ["no"], "vlayout": ["row"]
#   },
#   "relax_rules": {"disable_check_hdim_tile": false}
# }
# ---------------------------------------------------------------------------


def _load_custom_tune_config() -> Optional[dict]:
    path = os.environ.get("CK_TILE_FMHA_FWD_CUSTOM_TUNE_CONFIG_FILE", "").strip()
    if not path:
        return None
    with open(path, "r") as f:
        cfg = json.load(f)
    return cfg


def _tune_config_pick_base(target: str):
    # Same dispatch as the tail of `get_factory` below, but consulted only
    # to select the base class for a dynamic factory.
    if target.startswith("gfx950"):
        return KernelComponentFactoryGfx950
    if target.startswith("gfx9"):
        return KernelComponentFactoryGfx9
    if target.startswith("gfx115"):
        return KernelComponentFactoryGfx115
    if target.startswith("gfx11"):
        return KernelComponentFactoryGfx11
    if target.startswith("gfx125"):
        return KernelComponentFactoryGfx125
    if target.startswith("gfx12"):
        return KernelComponentFactoryGfx12
    raise Exception(f"Unsupported device target {target} in tune config")


def _parse_tune_config_tiles(tiles_by_dtype_json: dict) -> Dict[str, Dict[Tuple[int, int], List[FmhaFwdTileSize]]]:
    result: Dict[str, Dict[Tuple[int, int], List[FmhaFwdTileSize]]] = {}
    for dtype, hkey_map in tiles_by_dtype_json.items():
        by_hkey: Dict[Tuple[int, int], List[FmhaFwdTileSize]] = {}
        for hkey, tile_dicts in hkey_map.items():
            parts = [p.strip() for p in str(hkey).split(",")]
            if len(parts) != 2:
                raise ValueError(
                    f"[CustomTuneFactory] tile key '{hkey}' must be 'HDIM,HDIMV'"
                )
            hdim, hdim_v = int(parts[0]), int(parts[1])
            tiles: List[FmhaFwdTileSize] = []
            for td in tile_dicts:
                # Optional runtime dispatch constraint (custom-tune JSON only).
                # Kept purely as a string so it can carry arbitrary C++
                # boolean expressions referring to fmha_fwd_args `a` and
                # fmha_fwd_traits `t` (e.g. "a.max_seqlen_q < 704" or
                # "(a.max_seqlen_q >= 704 && a.max_seqlen_q < 1344) || ...").
                # Missing/empty -> keep default CppConstraint (== "true").
                _cc = td.get("cpp_constraint")
                _cc_str = str(_cc).strip() if _cc is not None else ""
                _constraint = (CppConstraint(bool_expr=_cc_str) if _cc_str
                               else CppConstraint())
                tiles.append(FmhaFwdTileSize(
                    F_bm0=int(td["F_bm0"]),
                    F_bn0=int(td["F_bn0"]),
                    F_bk0=int(td["F_bk0"]),
                    F_bn1=int(td["F_bn1"]),
                    F_bk1=int(td["F_bk1"]),
                    F_bk0max=int(td["F_bk0max"]),
                    F_rm0=int(td["F_rm0"]),
                    F_rn0=int(td["F_rn0"]),
                    F_rk0=int(td["F_rk0"]),
                    F_rm1=int(td["F_rm1"]),
                    F_rn1=int(td["F_rn1"]),
                    F_rk1=int(td["F_rk1"]),
                    F_wm0=int(td["F_wm0"]),
                    F_wn0=int(td["F_wn0"]),
                    F_wk0=int(td["F_wk0"]),
                    F_wm1=int(td["F_wm1"]),
                    F_wn1=int(td["F_wn1"]),
                    F_wk1=int(td["F_wk1"]),
                    F_occupancy=int(td["F_occupancy"]),
                    F_constraint=_constraint,
                ))
            by_hkey[(hdim, hdim_v)] = tiles
        result[dtype] = by_hkey
    return result


def _make_tune_filter_rule(filters: dict):
    if not filters:
        return None

    allowed_mode    = set(filters.get("mode", []))    or None
    allowed_mask    = set(filters.get("mask", []))    or None
    allowed_bias    = set(filters.get("bias", []))    or None
    allowed_lse     = set(filters.get("lse", []))     or None
    allowed_dropout = set(filters.get("dropout", [])) or None
    allowed_logits  = set(filters.get("logits", []))  or None
    allowed_qscale  = set(filters.get("qscale", []))  or None
    allowed_vlayout = set(filters.get("vlayout", [])) or None
    allowed_skip    = set(filters.get("skip", []))    or None
    allowed_sink    = set(filters.get("sink", []))    or None
    allowed_trload  = set(filters.get("trload", []))  or None
    allowed_spad    = set(filters.get("spad", []))    or None
    allowed_skpad   = set(filters.get("skpad", []))   or None
    allowed_dpad    = set(filters.get("dpad", []))    or None
    allowed_dvpad   = set(filters.get("dvpad", []))   or None

    def tune_filter(problem_ctx: "ProblemContext", kernel_ctx: "KernelContext") -> bool:
        p = kernel_ctx.pipeline
        if allowed_mode    is not None and problem_ctx.mode not in allowed_mode:    return False
        if allowed_mask    is not None and p.F_mask     not in allowed_mask:    return False
        if allowed_bias    is not None and p.F_bias     not in allowed_bias:    return False
        if allowed_lse     is not None and p.F_lse      not in allowed_lse:     return False
        if allowed_dropout is not None and p.F_dropout  not in allowed_dropout: return False
        if allowed_logits  is not None and p.F_logits   not in allowed_logits:  return False
        if allowed_qscale  is not None and p.F_qscale   not in allowed_qscale:  return False
        if allowed_vlayout is not None and p.F_vlayout  not in allowed_vlayout: return False
        if allowed_skip    is not None and p.F_skip     not in allowed_skip:    return False
        if allowed_sink    is not None and p.F_sink     not in allowed_sink:    return False
        if allowed_trload  is not None and p.F_trload   not in allowed_trload:  return False
        if allowed_spad    is not None and p.F_spad     not in allowed_spad:    return False
        if allowed_skpad   is not None and p.F_skpad    not in allowed_skpad:   return False
        if allowed_dpad    is not None and p.F_dpad     not in allowed_dpad:    return False
        if allowed_dvpad   is not None and p.F_dvpad    not in allowed_dvpad:   return False
        return True

    return tune_filter


def _build_custom_tune_factory(cfg: dict):
    target = cfg.get("target", "")
    if not target:
        raise ValueError("[CustomTuneFactory] JSON 'target' field is required")
    base = _tune_config_pick_base(target)

    tiles_by_dtype = _parse_tune_config_tiles(cfg.get("tiles", {}))
    dtypes_whitelist = tuple(cfg.get("dtypes", ()))
    extra_rule = _make_tune_filter_rule(cfg.get("filters", {}))
    disable_hdim_rule = bool(
        cfg.get("relax_rules", {}).get("disable_check_hdim_tile", False)
    )

    class CustomTuneFactory(base):
        # arch inherited from base

        @classmethod
        def supported_dtypes(cls) -> Tuple[str]:
            base_dt = base.supported_dtypes()
            if dtypes_whitelist:
                return tuple(d for d in base_dt if d in dtypes_whitelist)
            # If not explicitly listed, restrict to dtypes appearing in tiles.
            return tuple(d for d in base_dt if d in tiles_by_dtype)

        @classmethod
        def get_hdim_tile_size_dict(cls, dtype: str) -> Optional[dict]:
            return tiles_by_dtype.get(dtype, None)

        @classmethod
        def get_rules(cls) -> List[CompatibilityRule]:
            rules = list(base.get_rules())
            if disable_hdim_rule:
                rules = [
                    r for r in rules if getattr(r, "__name__", "") != "check_hdim_tile"
                ]
            if extra_rule is not None:
                rules.append(extra_rule)
            return rules

    CustomTuneFactory.__name__ = f"CustomTuneFactory_{base.__name__}"
    return CustomTuneFactory


def get_factory(target: str):
    # Highest priority: JSON-driven tune-config factory.
    tune_cfg = _load_custom_tune_config()
    if tune_cfg is not None:
        return _build_custom_tune_factory(tune_cfg)

    if os.environ.get("CK_TILE_FMHA_FWD_CUSTOM_FACTORY", "0") == "1":
        return CustomFactory

    # Place more specific architectures first

    if target.startswith("gfx950"):
        return KernelComponentFactoryGfx950
    if target.startswith("gfx9"):
        return KernelComponentFactoryGfx9
    if target.startswith("gfx115"):
        return KernelComponentFactoryGfx115
    if target.startswith("gfx11"):
        return KernelComponentFactoryGfx11
    if target.startswith("gfx125"):
        return KernelComponentFactoryGfx125
    if target.startswith("gfx12"):
        return KernelComponentFactoryGfx12

    raise Exception(f"Unsupported device target {target}")


@dataclass(frozen=True)
class Product:
    name: str
    rule: CompatibilityRule

    def __call__(self, problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
        return self.rule(problem_ctx, kernel_ctx)


def get_product(receipt: int) -> Product:
    # Flash attention integration
    if receipt == 2:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            cond = problem_ctx.dtype in ["fp16", "bf16"]
            cond &= kernel_ctx.pipeline.F_vlayout == "row"
            cond &= kernel_ctx.pipeline.F_bias in ["no", "alibi"]
            cond &= kernel_ctx.pipeline.F_qscale == "no"
            cond &= kernel_ctx.pipeline.F_skip == "f"
            cond &= kernel_ctx.pipeline.F_sink == "f"
            # FlashAttention direct fwd wrappers always use softcap disabled and LSE enabled.
            cond &= kernel_ctx.pipeline.F_logits == "f"
            cond &= kernel_ctx.pipeline.F_lse == "t"
            return cond

        return Product(name="Flash attention integration", rule=fit)
    # Receipt 3 forward coverage used by CK library / smoke tests
    elif receipt == 3:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            cond = problem_ctx.dtype in ["fp16", "bf16"]
            cond &= kernel_ctx.pipeline.F_vlayout == "row"
            cond &= kernel_ctx.pipeline.F_bias in ["no", "alibi", "bias"]
            cond &= kernel_ctx.pipeline.F_qscale == "no"
            cond &= kernel_ctx.pipeline.F_skip == "f"
            return cond

        return Product(name="Flash attention integration", rule=fit)
    # PyTorch integration
    elif receipt == 4:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            cond = problem_ctx.dtype in ["fp16", "bf16"]
            cond &= kernel_ctx.pipeline.F_vlayout == "row"
            cond &= kernel_ctx.pipeline.F_bias in ["no", "bias"]
            cond &= kernel_ctx.pipeline.F_qscale == "no"
            cond &= kernel_ctx.pipeline.F_skip == "f"
            cond &= kernel_ctx.pipeline.F_logits == "f"
            return cond

        return Product(name="PyTorch integration", rule=fit)
    # Aiter(mha_fwd) integration
    elif receipt == 100:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            cond = problem_ctx.dtype in ["fp16", "bf16", "fp8bf16"]
            cond &= problem_ctx.mode == "batch"
            cond &= kernel_ctx.pipeline.F_vlayout == "row"
            if problem_ctx.dtype == "fp8bf16":
                cond &= problem_ctx.hdim == 128 or problem_ctx.hdim == 192
            return cond

        return Product(name="Aiter(mha_fwd) integration", rule=fit)
    # Aiter(mha_varlen_fwd) integration
    elif receipt == 200:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            cond = problem_ctx.dtype in ["fp16", "bf16", "fp8bf16"]
            cond &= problem_ctx.mode == "group"
            cond &= kernel_ctx.pipeline.F_vlayout == "row"
            if problem_ctx.dtype == "fp8bf16":
                cond &= problem_ctx.hdim == 128 or problem_ctx.hdim == 192
            return cond

        return Product(name="Aiter(mha_varlen_fwd) integration", rule=fit)
    # aiter::mha_fwd C++ api integration
    elif receipt == 600:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            cond = problem_ctx.dtype in ["fp16", "bf16", "fp8bf16"]
            cond &= kernel_ctx.pipeline.F_vlayout == "row"
            if problem_ctx.dtype == "fp8bf16":
                cond &= problem_ctx.hdim == 128 or problem_ctx.hdim == 192
            return cond

        return Product(name="aiter::mha_fwd C++ api integration", rule=fit)
    # TransformerEngine integration
    elif receipt == 700:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            cond = problem_ctx.dtype in ["fp16", "bf16"]
            cond &= kernel_ctx.pipeline.F_vlayout == "row"
            cond &= kernel_ctx.pipeline.F_qscale == "no"
            cond &= kernel_ctx.pipeline.F_lse == "t"
            cond &= kernel_ctx.pipeline.F_skip == "f"
            cond &= kernel_ctx.pipeline.F_sink == "f"
            cond &= kernel_ctx.pipeline.F_logits == "f"
            return cond

        return Product(name="TransformerEngine integration", rule=fit)
    elif receipt == 888:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            cond = problem_ctx.dtype in ["fp8bf16", "fp8fp32"]
            cond &= kernel_ctx.pipeline.F_vlayout == "row"
            cond &= problem_ctx.hdim == 128 or problem_ctx.hdim == 192
            return cond

        return Product(name="receipt = 888", rule=fit)
    # fp32 only, all variations
    elif receipt == 800:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            cond = problem_ctx.dtype == "fp32"
            cond &= kernel_ctx.pipeline.F_skip == "f"
            cond &= kernel_ctx.pipeline.F_logits == "f"
            return cond

        return Product(name="fp32 only, all variations", rule=fit)
    # fp32 only, minimal set of parameters
    elif receipt == 801:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            cond = problem_ctx.dtype == "fp32"
            cond &= problem_ctx.hdim in [48, 128]
            cond &= problem_ctx.mode == "batch"
            cond &= kernel_ctx.pipeline.F_bias == "no"
            cond &= kernel_ctx.pipeline.F_lse == "f"
            cond &= kernel_ctx.pipeline.F_dropout == "f"
            cond &= kernel_ctx.pipeline.F_skip == "f"
            cond &= kernel_ctx.pipeline.F_logits == "f"
            cond &= kernel_ctx.pipeline.F_mask == "s_no"
            return cond

        return Product(name="fp32 only, minimal set of parameters", rule=fit)
    # Don't build fp32 by default
    else:

        def fit(problem_ctx: ProblemContext, kernel_ctx: KernelContext) -> bool:
            return problem_ctx.dtype != "fp32"

        return Product(name="Default", rule=fit)


def get_fwd_blobs(
    targets: List[str], kernel_filter: Optional[str], receipt, optdim_list, mask_impl
) -> Tuple[FmhaFwdApiPool, List[FmhaFwdKernel]]:
    gen = list()
    api_pool = FmhaFwdApiPool()

    factories = get_factories_for_targets(targets, get_factory)

    for factory, dtype in ((f, t) for f in factories for t in f.supported_dtypes()):
        d = factory.get_hdim_tile_size_dict(dtype)
        # CustomTuneFactory might return None
        if not d:
            continue
        # for hdim_str, mode, mask, bias, lse in itertools.product(d.keys(), MODE_MAP.keys(), MASK_MAP.keys(), ["t", "f"], ["t", "f"]):
        for ((hdim, hdim_v), tiles), mode in itertools.product(
            d.items(), MODE_MAP.keys()
        ):
            if optdim_list != [-1]:
                if hdim not in optdim_list:
                    continue
            for tile, next_tile in zip(tiles, tiles[1:]):
                assert next_tile.F_bm0 >= tile.F_bm0, (
                    "Tiles must be ordered by increasing bm0"
                )

            for tile, pipeline in itertools.product(
                tiles, factory.get_pipelines(dtype, hdim, hdim_v, receipt, mask_impl)
            ):
                problem_ctx = ProblemContext(
                    dtype=dtype, mode=mode, hdim=hdim, hdim_v=hdim_v
                )
                kernel_ctx = KernelContext(
                    tile=tile, pipeline=pipeline, mask_impl=mask_impl
                )
                rules = factory.get_rules()
                product = get_product(receipt)

                if not is_compatible(problem_ctx, kernel_ctx, [*rules, product]):
                    continue

                k = create_kernel(factory.arch, problem_ctx, kernel_ctx)
                if kernel_filter != "":
                    if not fnmatch.fnmatch(k.name, kernel_filter):
                        continue

                api_pool.register_traits(k.api_trait())
                gen.append(k)

    return (api_pool, gen)


def write_single_fwd_kernel(kernel: FmhaFwdKernel, autogen_dir: Path) -> None:
    update_file(autogen_dir / kernel.filename, kernel.render())


def write_fwd_api(
    api_pool: FmhaFwdApiPool,
    autogen_dir: Path,
) -> None:
    def accept_only_v3(trait: FmhaFwdApiTrait) -> bool:
        return trait.pipeline_tag == "qr_async_trload_v3"

    def accept_only_v2(trait: FmhaFwdApiTrait) -> bool:
        return not accept_only_v3(trait)

    content = "".join(
        [
            FMHA_FWD_API_HEADER,
            api_pool.render("fmha_fwd_v2", filter_fn=accept_only_v2),
            api_pool.render("fmha_fwd_v3", filter_fn=accept_only_v3),
            FMHA_FWD_API_FOOTER,
            api_pool.render_block_scale_size_kv(),
        ]
    )
    update_file(autogen_dir / FMHA_FWD_API_FILENAME, content)


def write_blobs(
    targets: List[str],
    output_dir: Path,
    kernel_filter: str,
    receipt,
    optdim_list,
    mask_impl,
) -> None:
    api_pool, kernels = get_fwd_blobs(
        targets, kernel_filter, receipt, optdim_list, mask_impl
    )
    for kernel in kernels:
        write_single_fwd_kernel(kernel, output_dir)
    write_fwd_api(api_pool, output_dir)


def list_blobs(
    targets: List[str],
    file_path: Path,
    kernel_filter: str,
    receipt,
    optdim_list,
    mask_impl,
) -> None:
    with file_path.open("a") as f:
        _, kernels = get_fwd_blobs(
            targets, kernel_filter, receipt, optdim_list, mask_impl
        )
        for kernel in kernels:
            f.write((file_path.parent / GEN_DIR / kernel.filename).as_posix() + "\n")
        f.write((file_path.parent / GEN_DIR / FMHA_FWD_API_FILENAME).as_posix() + "\n")
