"""
CK Tile backend implementation

Wraps CK Tile generated kernels from tile_engine codegen.
"""

import os
import re
import json
import time
from pathlib import Path
from typing import List, Dict, Optional
import numpy as np

from .base import KernelInstance, BackendBase, BackendType


class TileKernelInstance(KernelInstance):
    """
    Kernel instance for CK Tile generated kernels
    
    Wraps kernels generated by tile_engine/ops/gemm/gemm_instance_builder.py
    """
    
    def __init__(self, kernel_key, kernel_name: str, kernel_config: dict,
                 cpp_kernel=None):
        """
        Initialize tile kernel instance
        
        Args:
            kernel_key: KernelKey object
            kernel_name: Kernel name
            kernel_config: Kernel configuration dictionary
            cpp_kernel: Optional C++ kernel object (from bindings)
        """
        self._key = kernel_key
        self._name = kernel_name
        self._config = kernel_config
        self._cpp_kernel = cpp_kernel
    
    def get_key(self):
        """Get kernel key"""
        return self._key
    
    def supports(self, problem) -> bool:
        """
        Check if kernel supports the problem
        
        Checks:
        - Dimension divisibility (if no padding)
        - Resource constraints
        - Data type compatibility
        """
        # Get tile sizes from key
        tile_m = self._key.algorithm.tile_shape.m
        tile_n = self._key.algorithm.tile_shape.n
        tile_k = self._key.algorithm.tile_shape.k
        
        # Check if padding is enabled
        pad_m = self._config.get('pad_m', False)
        pad_n = self._config.get('pad_n', False)
        pad_k = self._config.get('pad_k', False)
        
        # If padding enabled, any size is supported
        if pad_m and pad_n and pad_k:
            return True
        
        # Check divisibility
        if not pad_m and problem.M % tile_m != 0:
            return False
        if not pad_n and problem.N % tile_n != 0:
            return False
        if not pad_k and problem.K % tile_k != 0:
            return False
        
        # Check resource constraints
        if hasattr(problem, 'smem_budget') and problem.smem_budget > 0:
            # Estimate shared memory usage
            smem_usage = self._estimate_smem_usage()
            if smem_usage > problem.smem_budget:
                return False
        
        return True
    
    def get_name(self) -> str:
        """Get kernel name"""
        return self._name
    
    def run(self, a, b, c, problem, stream=None) -> float:
        """
        Execute kernel
        
        Args:
            a: Input tensor A
            b: Input tensor B
            c: Output tensor C
            problem: Problem specification
            stream: Optional GPU stream
        
        Returns:
            Execution time in milliseconds
        """
        # If C++ kernel is available, use it
        if self._cpp_kernel is not None:
            return self._run_cpp_kernel(a, b, c, problem, stream)
        
        # Otherwise, use reference implementation
        return self._run_reference(a, b, c, problem)
    
    def _run_cpp_kernel(self, a, b, c, problem, stream) -> float:
        """Run using C++ kernel (via bindings)"""
        try:
            # Get data pointers
            a_ptr = self._get_data_ptr(a)
            b_ptr = self._get_data_ptr(b)
            c_ptr = self._get_data_ptr(c)
            
            # Call C++ kernel
            time_ms = self._cpp_kernel.run(a_ptr, b_ptr, c_ptr, problem, stream)
            return time_ms
        except Exception as e:
            # Fallback to reference
            print(f"Warning: C++ kernel failed ({e}), using reference")
            return self._run_reference(a, b, c, problem)
    
    def _run_reference(self, a, b, c, problem) -> float:
        """Run using NumPy reference implementation"""
        start = time.perf_counter()
        
        # Convert to numpy
        a_np = self._to_numpy(a)
        b_np = self._to_numpy(b)
        
        # Compute
        result = np.matmul(a_np, b_np)
        
        # Copy to output
        if isinstance(c, np.ndarray):
            np.copyto(c, result)
        else:
            # Try to copy back to device tensor
            try:
                import torch
                if isinstance(c, torch.Tensor):
                    c.copy_(torch.from_numpy(result))
            except:
                pass
        
        elapsed = (time.perf_counter() - start) * 1000
        return elapsed
    
    def get_backend_type(self) -> BackendType:
        """Get backend type"""
        return BackendType.TILE
    
    def _estimate_smem_usage(self) -> int:
        """Estimate shared memory usage in bytes"""
        # Simplified estimation based on tile sizes
        tile_m = self._key.algorithm.tile_shape.m
        tile_n = self._key.algorithm.tile_shape.n
        tile_k = self._key.algorithm.tile_shape.k
        
        # Assume FP16 (2 bytes per element)
        bytes_per_elem = 2
        
        # A tile + B tile
        smem_a = tile_m * tile_k * bytes_per_elem
        smem_b = tile_k * tile_n * bytes_per_elem
        
        # Double buffer if enabled
        if self._key.algorithm.double_buffer:
            return 2 * (smem_a + smem_b)
        else:
            return smem_a + smem_b
    
    def get_metadata(self) -> dict:
        """Get kernel metadata"""
        meta = super().get_metadata()
        meta.update({
            'tile_shape': (
                self._key.algorithm.tile_shape.m,
                self._key.algorithm.tile_shape.n,
                self._key.algorithm.tile_shape.k
            ),
            'wave_shape': (
                self._key.algorithm.wave_shape.m,
                self._key.algorithm.wave_shape.n,
                self._key.algorithm.wave_shape.k
            ),
            'pipeline': self._key.algorithm.pipeline.value if hasattr(self._key.algorithm.pipeline, 'value') else str(self._key.algorithm.pipeline),
            'persistent': self._key.algorithm.persistent,
            'config': self._config,
        })
        return meta


class TileBackend(BackendBase):
    """
    Backend for CK Tile generated kernels
    
    Discovers and creates kernel instances from tile_engine codegen output.
    """
    
    def __init__(self):
        """Initialize tile backend"""
        self._cpp_backend = None
        self._load_cpp_backend()
    
    def _load_cpp_backend(self):
        """Try to load C++ backend"""
        try:
            from .. import _ck_dispatcher_cpp
            if hasattr(_ck_dispatcher_cpp, 'TileBackend'):
                self._cpp_backend = _ck_dispatcher_cpp.TileBackend()
        except ImportError:
            pass
    
    def discover_kernels(self, search_path: str) -> List[KernelInstance]:
        """
        Discover CK Tile kernels from codegen output
        
        Args:
            search_path: Path to generated kernel directory
        
        Returns:
            List of TileKernelInstance objects
        """
        search_path = Path(search_path)
        
        if not search_path.exists():
            return []
        
        kernels = []
        
        # Look for generated header files
        for header_file in search_path.glob("**/*.hpp"):
            try:
                kernel = self._parse_kernel_header(header_file)
                if kernel:
                    kernels.append(kernel)
            except Exception as e:
                print(f"Warning: Failed to parse {header_file}: {e}")
        
        # Also look for JSON manifest files
        for json_file in search_path.glob("**/*_manifest.json"):
            try:
                kernel_list = self._parse_manifest(json_file)
                kernels.extend(kernel_list)
            except Exception as e:
                print(f"Warning: Failed to parse {json_file}: {e}")
        
        return kernels
    
    def _parse_kernel_header(self, header_file: Path) -> Optional[TileKernelInstance]:
        """
        Parse generated kernel header file
        
        Extracts metadata from static constexpr members and comments.
        """
        with open(header_file, 'r') as f:
            content = f.read()
        
        # Extract kernel name
        kernel_name_match = re.search(r'constexpr const char\* KERNEL_NAME\s*=\s*"([^"]+)"', content)
        if not kernel_name_match:
            return None
        
        kernel_name = kernel_name_match.group(1)
        
        # Extract tile configuration
        tile_m = self._extract_constexpr(content, 'TileM')
        tile_n = self._extract_constexpr(content, 'TileN')
        tile_k = self._extract_constexpr(content, 'TileK')
        
        if not all([tile_m, tile_n, tile_k]):
            return None
        
        # Build kernel config
        config = {
            'tile_m': tile_m,
            'tile_n': tile_n,
            'tile_k': tile_k,
            'source_file': str(header_file),
        }
        
        # Extract other parameters
        config['block_size'] = self._extract_constexpr(content, 'BlockSize', 256)
        config['pad_m'] = self._extract_bool(content, 'kPadM', False)
        config['pad_n'] = self._extract_bool(content, 'kPadN', False)
        config['pad_k'] = self._extract_bool(content, 'kPadK', False)
        config['persistent'] = self._extract_bool(content, 'UsePersistentKernel', False)
        config['double_buffer'] = self._extract_bool(content, 'DoubleSmemBuffer', False)
        
        # Create kernel key (simplified - would need full parsing)
        from ..core import KernelKey, Signature, Algorithm, TileShape, WaveShape, WarpTileShape
        from ..core import DataType, LayoutTag, Pipeline, Epilogue, Scheduler
        
        kernel_key = KernelKey(
            signature=Signature(
                dtype_a=DataType.FP16,
                dtype_b=DataType.FP16,
                dtype_c=DataType.FP16,
                dtype_acc=DataType.FP32,
                layout_a=LayoutTag.ROW_MAJOR,
                layout_b=LayoutTag.COL_MAJOR,
                layout_c=LayoutTag.ROW_MAJOR,
                transpose_a=False,
                transpose_b=False,
                grouped=False,
                split_k=1,
                elementwise_op="PassThrough",
                num_d_tensors=0,
                structured_sparsity=False,
            ),
            algorithm=Algorithm(
                tile_shape=TileShape(m=tile_m, n=tile_n, k=tile_k),
                wave_shape=WaveShape(m=2, n=2, k=1),
                warp_tile_shape=WarpTileShape(m=32, n=32, k=16),
                pipeline=Pipeline.COMP_V4,
                scheduler=Scheduler.INTRAWAVE,
                epilogue=Epilogue.CSHUFFLE,
                block_size=config['block_size'],
                double_buffer=config['double_buffer'],
                persistent=config['persistent'],
                preshuffle=False,
                transpose_c=False,
                num_wave_groups=1,
            ),
            gfx_arch=942,
        )
        
        return TileKernelInstance(kernel_key, kernel_name, config)
    
    def _parse_manifest(self, json_file: Path) -> List[TileKernelInstance]:
        """Parse JSON manifest file"""
        with open(json_file, 'r') as f:
            manifest = json.load(f)
        
        kernels = []
        for kernel_config in manifest.get('kernels', []):
            try:
                kernel = self.create_kernel_instance(kernel_config)
                kernels.append(kernel)
            except Exception as e:
                print(f"Warning: Failed to create kernel from manifest: {e}")
        
        return kernels
    
    def create_kernel_instance(self, kernel_config: dict) -> TileKernelInstance:
        """Create kernel instance from configuration"""
        # This would create a full KernelKey from the config
        # Simplified implementation
        raise NotImplementedError("Full kernel creation from config not yet implemented")
    
    def get_backend_type(self) -> BackendType:
        """Get backend type"""
        return BackendType.TILE
    
    @staticmethod
    def _extract_constexpr(content: str, name: str, default=None):
        """Extract constexpr value from header"""
        pattern = rf'constexpr\s+(?:static\s+)?(?:const\s+)?(?:int|std::size_t|auto)\s+{name}\s*=\s*(\d+)'
        match = re.search(pattern, content)
        return int(match.group(1)) if match else default
    
    @staticmethod
    def _extract_bool(content: str, name: str, default: bool) -> bool:
        """Extract boolean constexpr from header"""
        pattern = rf'constexpr\s+(?:static\s+)?(?:const\s+)?bool\s+{name}\s*=\s*(true|false)'
        match = re.search(pattern, content)
        return match.group(1) == 'true' if match else default

